URL,节点数量,状态,错误信息
https://api.xjichang.buzz/api/v1/client/subscribe?token=2ae1552e6170462ffd7ba62f6415041c,0,失败,"请求失败: HTTPSConnectionPool(host='api.xjichang.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=2ae1552e6170462ffd7ba62f6415041c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cc100>: Failed to resolve 'api.xjichang.buzz' ([Errno -2] Name or service not known)""))"
https://41be350f-5079-4195-8329-f6fa25f9906a.com/api/v1/client/subscribe?token=457b027ae93dddebfdecf605356b014f,0,失败,"请求失败: HTTPSConnectionPool(host='41be350f-5079-4195-8329-f6fa25f9906a.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=457b027ae93dddebfdecf605356b014f (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cf9a0>: Failed to resolve '41be350f-5079-4195-8329-f6fa25f9906a.com' ([Errno -2] Name or service not known)""))"
https://41be350f-5079-4195-8329-f6fa25f9906a.com/api/v1/client/subscribe?token=b2f322d153d1f09929cecc01a46b1086,0,失败,"请求失败: HTTPSConnectionPool(host='41be350f-5079-4195-8329-f6fa25f9906a.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=b2f322d153d1f09929cecc01a46b1086 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf131f0>: Failed to resolve '41be350f-5079-4195-8329-f6fa25f9906a.com' ([Errno -2] Name or service not known)""))"
http://py.kjol.cc/tube,0,失败,"请求失败: HTTPConnectionPool(host='py.kjol.cc', port=80): Max retries exceeded with url: /tube (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf13d90>: Failed to resolve 'py.kjol.cc' ([Errno -2] Name or service not known)""))"
http://dd.cxld.sbs/api/v1/client/subscribe?token=8bdfea8d0a392993aebab184b7c367f5,0,失败,"请求失败: HTTPConnectionPool(host='dd.cxld.sbs', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8bdfea8d0a392993aebab184b7c367f5 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3e110>: Failed to resolve 'dd.cxld.sbs' ([Errno -2] Name or service not known)""))"
http://sub.duckcloud.cc/api/v1/client/subscribe?token=0d4fb20201a60f66d82560943d242134,0,失败,"请求失败: HTTPConnectionPool(host='sub.duckcloud.cc', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=0d4fb20201a60f66d82560943d242134 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3d570>: Failed to resolve 'sub.duckcloud.cc' ([Errno -2] Name or service not known)""))"
https://20240802.canadapost-vip.com/api/v1/client/subscribe?token=1ca297e96863f96d98459036674a40f1,0,失败,"请求失败: HTTPSConnectionPool(host='20240802.canadapost-vip.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=1ca297e96863f96d98459036674a40f1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf68460>: Failed to resolve '20240802.canadapost-vip.com' ([Errno -2] Name or service not known)""))"
http://jichang.miaoge110.cf/api/v1/client/subscribe?token=c10dc57190300e07b0091abb70b6f148,0,失败,"请求失败: HTTPConnectionPool(host='jichang.miaoge110.cf', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c10dc57190300e07b0091abb70b6f148 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3f880>: Failed to resolve 'jichang.miaoge110.cf' ([Errno -2] Name or service not known)""))"
https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=b85860db9401eaa35299b79e0e866463,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=b85860db9401eaa35299b79e0e866463
https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=afc10da32cc774b8e72ee887d1edf7a5,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=afc10da32cc774b8e72ee887d1edf7a5
https://5.52vpn.xyz/link/vdfk8bfyqpsz9zch?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='5.52vpn.xyz', port=443): Max retries exceeded with url: /link/vdfk8bfyqpsz9zch?clash=1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1017)')))"
http://s1.subcsyun.online/api/v1/client/subscribe?token=2354a92f0ce651a3b8ecfef4a45b52c0,0,成功,
https://123sdm.xyz/api/v1/client/subscribe?token=5a88c90b5c99708bb403ce09eb227f15,0,失败,"请求失败: HTTPSConnectionPool(host='123sdm.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5a88c90b5c99708bb403ce09eb227f15 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3d3c0>: Failed to resolve '123sdm.xyz' ([Errno -2] Name or service not known)""))"
https://a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz/api/v1/client/subscribe?token=2c0d6450f5c12ef56049f0ad77b356bf,0,失败,"请求失败: HTTPSConnectionPool(host='a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=2c0d6450f5c12ef56049f0ad77b356bf (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3fe50>: Failed to resolve 'a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz' ([Errno -2] Name or service not known)""))"
https://a76.aaa7.info/ease/link?token=a60d2ad70dbfaf49ad35263499382f3b,0,失败,请求失败: 403 Client Error: Forbidden for url: https://a76.aaa7.info/ease/link?token=a60d2ad70dbfaf49ad35263499382f3b
https://595780.xyz/api/v1/client/subscribe?token=675d2fd1e7221fe2ce884f3f097d914a,0,失败,请求失败: 403 Client Error: Forbidden for url: https://595780.xyz/api/v1/client/subscribe?token=675d2fd1e7221fe2ce884f3f097d914a
https://a.kuaicloud.xyz/link/OcovI3H3crv7Zj4E?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/OcovI3H3crv7Zj4E?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf115d0>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://3h.lv/api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c,0,失败,"请求失败: HTTPSConnectionPool(host='3h.lv', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1d780>: Failed to resolve '3h.lv' ([Errno -2] Name or service not known)""))"
http://www.nicevpns.com/api/v1/client/subscribe?token=d9d49c05b1c505b6f88d2198c1ed7ee7,0,成功,
https://api.ssrnode.cc/link/wwFws3cfhmAbSE8q?clash=1,0,失败,内容过短
https://adobe.zhuzhu12.com/link/rbPHm87z7HiuVw68?sub=3&amp;extend=1,0,成功,
https://api.xqc.best/api/v1/client/subscribe?token=1aa3685e5b5733edf53f0655a23df9af,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=1aa3685e5b5733edf53f0655a23df9af (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://3.cundu.eu.org/233?clash,0,失败,"请求失败: HTTPSConnectionPool(host='3.cundu.eu.org', port=443): Max retries exceeded with url: /233?clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf11900>: Failed to resolve '3.cundu.eu.org' ([Errno -2] Name or service not known)""))"
https://app.jisovpn.site/api/v1/client/subscribe?token=352049eecc0d30658488bcf11184018e,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=352049eecc0d30658488bcf11184018e (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf11420>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
https://001.6891256.xyz/api/v1/client/subscribe?token=0bce074e322a6f5a7d27508c11a67f4a,0,失败,"请求失败: HTTPSConnectionPool(host='001.6891256.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=0bce074e322a6f5a7d27508c11a67f4a (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f550>: Failed to resolve '001.6891256.xyz' ([Errno -2] Name or service not known)""))"
https://41be350f-5079-4195-8329-f6fa25f9906a.com/api/v1/client/subscribe?token=44225106b5b106100b52a68f7a3a7a53,0,失败,"请求失败: HTTPSConnectionPool(host='41be350f-5079-4195-8329-f6fa25f9906a.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=44225106b5b106100b52a68f7a3a7a53 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1e770>: Failed to resolve '41be350f-5079-4195-8329-f6fa25f9906a.com' ([Errno -2] Name or service not known)""))"
https://api1.441166.xyz/api/v1/client/subscribe?token=19899def3463b7e9b7e9a819372f3638,0,失败,"请求失败: HTTPSConnectionPool(host='api1.441166.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=19899def3463b7e9b7e9a819372f3638 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1d6f0>: Failed to resolve 'api1.441166.xyz' ([Errno -2] Name or service not known)""))"
https://a.kuaicloud.xyz/link/E3BVs3jzQyTsywcG?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/E3BVs3jzQyTsywcG?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1f310>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
http://beautyandbeast.link/api/v1/client/subscribe?token=5230b5981566b0bbb413028dc8c33e39,0,成功,
https://520748.xyz/api/v1/client/subscribe?token=caf2f682b0b11eaa800cc13d3c96fdc4,0,失败,"请求失败: HTTPSConnectionPool(host='520748.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=caf2f682b0b11eaa800cc13d3c96fdc4 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8430>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
https://209966.xyz/api/v1/client/subscribe?token=8d3ff46616e85e3f4a309818717b8e65,0,失败,"请求失败: HTTPSConnectionPool(host='209966.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=8d3ff46616e85e3f4a309818717b8e65 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf68dc0>: Failed to resolve '209966.xyz' ([Errno -5] No address associated with hostname)""))"
https://api.shin-x.top/api/v1/client/subscribe?token=f366a4d533cf2f5f26bdecbbc54496b3,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.shin-x.top/api/v1/client/subscribe?token=f366a4d533cf2f5f26bdecbbc54496b3
https://api.zzzzzl.me/api/v1/client/subscribe?token=e9b56f3eafe135ead8f7785a9a5e6c10,0,失败,"请求失败: HTTPSConnectionPool(host='api.zzzzzl.me', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e9b56f3eafe135ead8f7785a9a5e6c10 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cead0>: Failed to resolve 'api.zzzzzl.me' ([Errno -2] Name or service not known)""))"
http://one.bblinks.top/user/gameservers?token=b9cc6a27b42a70106a881f5f24f3cb17,0,成功,
https://51fan.one/api/v1/client/subscribe?token=90c8cd3d1ff718175f535a73efc40f54,0,失败,请求失败: 403 Client Error: Forbidden for url: https://51fan.one/api/v1/client/subscribe?token=90c8cd3d1ff718175f535a73efc40f54
http://dd.ewmld2.one/api/v1/client/subscribe?token=171459f25a9af7a90f67c4a79e312645,0,失败,"请求失败: HTTPConnectionPool(host='dd.ewmld2.one', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=171459f25a9af7a90f67c4a79e312645 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1e7d0>: Failed to resolve 'dd.ewmld2.one' ([Errno -2] Name or service not known)""))"
https://aini.200566.xyz/tzjz55/download/%E7%BE%8E%E5%9B%BD%E8%87%AA%E5%BB%BA%E8%8A%82%E7%82%B9,0,失败,"请求失败: HTTPSConnectionPool(host='aini.200566.xyz', port=443): Max retries exceeded with url: /tzjz55/download/%E7%BE%8E%E5%9B%BD%E8%87%AA%E5%BB%BA%E8%8A%82%E7%82%B9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f0d0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://202503212313501.chibaba.ggff.net/api/v1/client/subscribe?token=eee1b58c52d8e656bc6b729a182cf49b,0,失败,请求失败: 403 Client Error: Forbidden for url: https://202503212313501.chibaba.ggff.net/api/v1/client/subscribe?token=eee1b58c52d8e656bc6b729a182cf49b
http://panda.xn--i8sx78aisa52z.com/api/v1/client/subscribe?token=6d6ce997bff58396d7e9760e7a56c3b1,0,成功,
http://dashabi.ping-zi-yun.icu/api/v1/client/subscribe?token=08b9a8c1cbf7d387c6229418ee83c5d0#subscribe?token=08b9a8c1cbf7d387c6229418ee83c5d0,0,失败,"请求失败: HTTPConnectionPool(host='dashabi.ping-zi-yun.icu', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=08b9a8c1cbf7d387c6229418ee83c5d0 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3ffa0>: Failed to resolve 'dashabi.ping-zi-yun.icu' ([Errno -2] Name or service not known)""))"
http://www.freeflyingcloud.xyz/api/v1/client/subscribe?token=6d589576c74cf02da06f8b10d99011f4,0,成功,
https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=811e9d6ddaeeaef79d4443d9a6e57ab7,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=811e9d6ddaeeaef79d4443d9a6e57ab7
https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=fd3e1d86aff6d9c3f7c191e4e6959495,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=fd3e1d86aff6d9c3f7c191e4e6959495
http://www.e300daniu.com/api/v1/client/subscribe?token=9a7eea811c3493d74b74a96b2f0e7fd5,0,失败,"请求失败: HTTPConnectionPool(host='www.e300daniu.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=9a7eea811c3493d74b74a96b2f0e7fd5 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf69900>: Failed to resolve 'www.e300daniu.com' ([Errno -5] No address associated with hostname)""))"
https://569cdn.1010520.click/api/v1/client/subscribe?token=781d7319768d475772927420bc2a0274,0,失败,内容过短
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=5cb24ce689fecdb776dbcc0f5c29fde5,26,成功,
https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=af859bb658c5c454bc24b284d5e36e79,0,失败,请求失败: 403 Client Error: Forbidden for url: https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=af859bb658c5c454bc24b284d5e36e79
https://441133.xyz/link/9on12MKEZKxM8J51?clash=1,0,失败,内容过短
http://laobideng.xyz/api/v1/client/subscribe?token=cf6db2a5f3ca429db4580bc258f1d2b0,0,成功,
https://api.xinyo.vip/api/v1/client/subscribe?token=731485d80bbbde226e16ffac57a57554,2,成功,
https://20240802.canadapost-vip.com/api/v1/client/subscribe?token=c73b01ede92ec73221721267c6521d28,0,失败,"请求失败: HTTPSConnectionPool(host='20240802.canadapost-vip.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c73b01ede92ec73221721267c6521d28 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f250>: Failed to resolve '20240802.canadapost-vip.com' ([Errno -2] Name or service not known)""))"
https://aiosjhdy.forbit-api.boats/sub?token=26b76a9fc511fe18702c92ccf9ee6933,0,失败,"请求失败: HTTPSConnectionPool(host='aiosjhdy.forbit-api.boats', port=443): Max retries exceeded with url: /sub?token=26b76a9fc511fe18702c92ccf9ee6933 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1f130>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://dy.xyyjc.top/api/v1/client/subscribe?token=cc9fc6673e7c2400305f5fc19fc1f80f,0,成功,
http://ytjs.fun/api/v1/client/subscribe?token=5e80feb0196730cdd06b9ff939968a38,0,失败,"请求失败: HTTPConnectionPool(host='ytjs.fun', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=5e80feb0196730cdd06b9ff939968a38 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8eca260>: Failed to resolve 'ytjs.fun' ([Errno -2] Name or service not known)""))"
https://569cdn.1010520.click/api/v1/client/subscribe?token=d273183250f1dadc7c5bb9a2ebec31b9,0,失败,内容过短
http://www.a100.sbs/api/v1/client/subscribe?token=434839da2063207352bc5ec17d909eab,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ww38.a100.sbs/api/v1/client/subscribe?token=434839da2063207352bc5ec17d909eab
http://103.196.20.127/api/v1/client/subscribe?token=b54e2034bcbba8e8e982f368d6b49fab,0,失败,"请求失败: HTTPConnectionPool(host='103.196.20.127', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=b54e2034bcbba8e8e982f368d6b49fab (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8ecae90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://sub.966888.xyz/api/v1/client/subscribe?token=7b77ede392015975e9af44bd33ac3b2c,15,成功,
https://apps.apple.com/app/stash/id1596063349,0,成功,
https://amatrixap.com/link/hcpI9GQWdrZBS2QW?clash=1,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/hcpI9GQWdrZBS2QW?clash=1
https://app.lwjyj.com/api/v1/client/subscribe?token=f37074df7d5766abab6c29d863f50faa,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.lwjyj.com/api/v1/client/subscribe?token=f37074df7d5766abab6c29d863f50faa
http://46.8.226.171:11202/rwuzfPrv7HxsnBOLg3TqEbWJ,0,失败,"请求失败: HTTPConnectionPool(host='46.8.226.171', port=11202): Max retries exceeded with url: /rwuzfPrv7HxsnBOLg3TqEbWJ (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf68be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://app.tline.website/link/I7zdVzJTbbxGjMWf?sub=3&amp;pure,0,成功,
http://dy.changyouvpn.top/api/v1/client/subscribe?token=4e85554dae1c9858676693ae38d50c15,0,失败,内容过短
https://441133.xyz/link/9on12MKEZKxM8J51?sub=3,0,失败,内容过短
https://1122331.xyz/link/sxiur22as74ydcd3?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='1122331.xyz', port=443): Max retries exceeded with url: /link/sxiur22as74ydcd3?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf121a0>: Failed to resolve '1122331.xyz' ([Errno -5] No address associated with hostname)""))"
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=ff5fd444baaadb92d8aaa3040855b24e,0,失败,请求失败: 403 Client Error: Forbidden for url: https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=ff5fd444baaadb92d8aaa3040855b24e
https://66c6d6.whisperingbreeze.cc/api/v1/client/subscribe?token=a5b5e1841a739fb0976ae0c2ea764848,0,失败,内容过短
http://www.bfyun.top/api/v1/client/subscribe?token=a878f837dd8a4019e1e80a7122f417ee,0,失败,"请求失败: HTTPConnectionPool(host='www.bfyun.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=a878f837dd8a4019e1e80a7122f417ee (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1e1a0>: Failed to resolve 'www.bfyun.top' ([Errno -2] Name or service not known)""))"
http://ciallo.elegy.icu:7001/api/v1/client/subscribe?token=cdd2fe8c61c6faee53b0caca6b5123f3,0,失败,"请求失败: HTTPConnectionPool(host='ciallo.elegy.icu', port=7001): Max retries exceeded with url: /api/v1/client/subscribe?token=cdd2fe8c61c6faee53b0caca6b5123f3 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf12260>: Failed to resolve 'ciallo.elegy.icu' ([Errno -2] Name or service not known)""))"
http://www.qianlong520.top/api/v1/client/subscribe?token=a80aeac8c6bed1587f1353369467da7d,0,失败,"请求失败: HTTPConnectionPool(host='www.qianlong520.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=a80aeac8c6bed1587f1353369467da7d (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf106a0>: Failed to resolve 'www.qianlong520.top' ([Errno -2] Name or service not known)""))"
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=7e0b3996a0aaf1bf13c0a7ba55ca11fe,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=7e0b3996a0aaf1bf13c0a7ba55ca11fe
https://api.kuangbiaoyun.com/api/v1/client/subscribe?token=2ee32aa9a6c005e68e5b36a7f551927c,0,失败,"请求失败: HTTPSConnectionPool(host='api.kuangbiaoyun.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=2ee32aa9a6c005e68e5b36a7f551927c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f820>: Failed to resolve 'api.kuangbiaoyun.com' ([Errno -5] No address associated with hostname)""))"
https://231787.xyz/api/v1/client/subscribe?token=8cf303d3208521af8e95012212492720,0,失败,内容过短
https://209966.xyz/link/sRr8zgMz43EJRZ9C?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='209966.xyz', port=443): Max retries exceeded with url: /link/sRr8zgMz43EJRZ9C?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf68ee0>: Failed to resolve '209966.xyz' ([Errno -5] No address associated with hostname)""))"
https://api.ikuuu.science/link/u1yCJ1lZdhQ7J5JI?clash=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.ikuuu.science/link/u1yCJ1lZdhQ7J5JI?clash=3
http://fanqiang88.top/fanqiang88?token=c05c76f56b4079bda0689113b498af74,0,失败,请求失败: 404 Client Error: Not Found for url: http://fanqiang88.top/fanqiang88?token=c05c76f56b4079bda0689113b498af74
https://api.xjichang.buzz/api/v1/client/subscribe?token=49586945494cfc7e4fb8aead0d64b409,0,失败,"请求失败: HTTPSConnectionPool(host='api.xjichang.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=49586945494cfc7e4fb8aead0d64b409 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1e500>: Failed to resolve 'api.xjichang.buzz' ([Errno -2] Name or service not known)""))"
http://dy.luoxin.fun/link/THB5482nk37XUtvL?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='dy.luoxin.fun', port=80): Max retries exceeded with url: /link/THB5482nk37XUtvL?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf11510>: Failed to resolve 'dy.luoxin.fun' ([Errno -2] Name or service not known)""))"
https://api.zuanshivpn.cn/subscribe/shadowrocket/MGNmNTIwMTYtYmE5OC0zMTlkLWRlOGMtODRkYmZhYzljY2Nj,2,成功,
http://v2board.mcark.tk/api/v1/client/subscribe?token=efcb3c470fbfb10f5afa1b12f446b1c2,0,失败,"请求失败: HTTPConnectionPool(host='v2board.mcark.tk', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=efcb3c470fbfb10f5afa1b12f446b1c2 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1f0a0>: Failed to resolve 'v2board.mcark.tk' ([Errno -2] Name or service not known)""))"
https://api.zzzzzl.me/api/v1/client/subscribe?token=e9b56f3eafe135ead8f7785a9a5e6c10&amp;flag=meta,0,失败,"请求失败: HTTPSConnectionPool(host='api.zzzzzl.me', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e9b56f3eafe135ead8f7785a9a5e6c10&amp;flag=meta (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf6a800>: Failed to resolve 'api.zzzzzl.me' ([Errno -2] Name or service not known)""))"
https://2xulifestyle.com/api/v1/client/subscribe?token=6f704de593f392ceb1acda012d21cbdd,0,失败,"请求失败: HTTPSConnectionPool(host='2xulifestyle.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=6f704de593f392ceb1acda012d21cbdd (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf6bf70>: Failed to resolve '2xulifestyle.com' ([Errno -2] Name or service not known)""))"
https://api.xinyo.vip/api/v1/client/subscribe?token=718c5eaacce57a2f249ab7162a7e976d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xinyo.vip/api/v1/client/subscribe?token=718c5eaacce57a2f249ab7162a7e976d
https://a47cbea8-e7c5-3977-9cdc-5b83e50a6d48.subdotu.com/link/DgdybbHYgBprhupR?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a47cbea8-e7c5-3977-9cdc-5b83e50a6d48.subdotu.com', port=443): Max retries exceeded with url: /link/DgdybbHYgBprhupR?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f5e0>: Failed to resolve 'a47cbea8-e7c5-3977-9cdc-5b83e50a6d48.subdotu.com' ([Errno -2] Name or service not known)""))"
http://www.e300daniu.com/api/v1/client/subscribe?token=1a9bb164f11ff244197d042b7418bc34,0,失败,"请求失败: HTTPConnectionPool(host='www.e300daniu.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=1a9bb164f11ff244197d042b7418bc34 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf12200>: Failed to resolve 'www.e300daniu.com' ([Errno -5] No address associated with hostname)""))"
https://acl.syyn.pw/api/v1/client/subscribe?token=b42590abeb74298050a5601f23e19201,0,失败,请求失败: 403 Client Error: Forbidden for url: https://acl.syyn.pw/api/v1/client/subscribe?token=b42590abeb74298050a5601f23e19201
https://1st.sub-airport.com/api/v1/client/subscribe?token=5ef4ec7751819025fcba66de831dd380,0,失败,"请求失败: HTTPSConnectionPool(host='1st.sub-airport.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5ef4ec7751819025fcba66de831dd380 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf12110>: Failed to resolve '1st.sub-airport.com' ([Errno -2] Name or service not known)""))"
http://372ae8252c9ce608c5f7066f2177dfb1.52pokemon.top/api/v1/client/subscribe?token=1ab3efabd1e55383dd419b5c98f1e3de,0,失败,"请求失败: HTTPConnectionPool(host='372ae8252c9ce608c5f7066f2177dfb1.52pokemon.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=1ab3efabd1e55383dd419b5c98f1e3de (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1de70>: Failed to resolve '372ae8252c9ce608c5f7066f2177dfb1.52pokemon.top' ([Errno -2] Name or service not known)""))"
https://a.fsyun.xyz/api/v1/client/subscribe?token=e897b3435834a15f5329550262927d64,0,失败,"请求失败: HTTPSConnectionPool(host='a.fsyun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e897b3435834a15f5329550262927d64 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1e380>: Failed to resolve 'a.fsyun.xyz' ([Errno -2] Name or service not known)""))"
https://api-qw.02000.net/api/v1/client/subscribe?token=9f7ba2cb52d1928d9e6675f9558aeb5f,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api-qw.02000.net/api/v1/client/subscribe?token=9f7ba2cb52d1928d9e6675f9558aeb5f
http://146.235.63.28:21953/api/v1/client/subscribe?token=bf1367667592563e68ec5a2e6eeacf01,0,失败,"请求失败: HTTPConnectionPool(host='146.235.63.28', port=21953): Max retries exceeded with url: /api/v1/client/subscribe?token=bf1367667592563e68ec5a2e6eeacf01 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf12ce0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://app.cloudlion.me/api/v1/client/subscribe?token=c0893ab776d761f1b351b3e7e5cd366c,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=c0893ab776d761f1b351b3e7e5cd366c
https://16th.sub-airport.com/api/v1/client/subscribe?token=f9ff9457723b9583c3e585e2cbf8fb62,0,失败,"请求失败: HTTPSConnectionPool(host='16th.sub-airport.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f9ff9457723b9583c3e585e2cbf8fb62 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8be0>: Failed to resolve '16th.sub-airport.com' ([Errno -2] Name or service not known)""))"
https://66c4d4.brighthorizon.cc/api/v1/client/subscribe?token=7b6db52e41f1c99695fad4a10061ce28,0,失败,请求失败: 403 Client Error: Forbidden for url: https://66c4d4.brighthorizon.cc/api/v1/client/subscribe?token=7b6db52e41f1c99695fad4a10061ce28
https://4b8kse.babaivip.top/api/v1/client/subscribe?token=0631b0e70e123fd5c1bb9ff2bff2cda6,5,成功,
http://2983839.xyz/api/v1/client/subscribe?token=22083212ac7b948010541f105088404a,0,失败,"请求失败: HTTPConnectionPool(host='2983839.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=22083212ac7b948010541f105088404a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed98d0>: Failed to resolve '2983839.xyz' ([Errno -2] Name or service not known)""))"
http://dy.changyouVPN.top/api/v1/client/subscribe?token=2d4a161571330be113d2710100caa913,0,失败,内容过短
https://3661939e-fa11-4abc-a196-088938fc027a.fengchenginx.com/api/v1/client/subscribe?token=989eafc14c1343c2e21463d2f74ed84e,0,失败,"请求失败: HTTPSConnectionPool(host='3661939e-fa11-4abc-a196-088938fc027a.fengchenginx.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=989eafc14c1343c2e21463d2f74ed84e (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf11de0>: Failed to resolve '3661939e-fa11-4abc-a196-088938fc027a.fengchenginx.com' ([Errno -2] Name or service not known)""))"
https://api.hk03.fysub.com/link/7CIy6X3mmoHQOPPV?sub=3,0,失败,内容过短
http://188.213.196.100:8585/trojan/sub,0,失败,"请求失败: HTTPConnectionPool(host='188.213.196.100', port=8585): Max retries exceeded with url: /trojan/sub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf12260>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://ggiuwegivhe123.a123.bond/api/v1/client/subscribe?token=b2ce02fd201c9e5253a27566518c1e25,0,失败,请求失败: 404 Client Error: Not Found for url: http://ggiuwegivhe123.a123.bond/api/v1/client/subscribe?token=b2ce02fd201c9e5253a27566518c1e25
http://47.243.59.73/api/v1/client/subscribe?token=f872370768e7e2d6a36c7c1bb5d7f370,0,失败,内容过短
https://1.ovofast.xyz/api/v1/client/subscribe?token=d501ddb4e29dff226e226278c9d2b262,0,成功,
https://3h.lv/api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c&amp;flag=clash,0,失败,"请求失败: HTTPSConnectionPool(host='3h.lv', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c&amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf6b430>: Failed to resolve '3h.lv' ([Errno -2] Name or service not known)""))"
http://lianjiasub.work/api/v1/client/subscribe?token=b39bd2e21a2d1975ee0a0a4b7d5a1a3d,0,失败,内容过短
http://dy.hpyjc.top/api/v1/client/subscribe?token=8eba1d79f60c7e699cc0ce771b68a2c4,0,成功,
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;amp;flag=v2ray,0,成功,
https://a.aikllc.tech/api/v1/client/subscribe?token=bb0b4de5961dc7baf37398cc24c45eb7,0,失败,"请求失败: HTTPSConnectionPool(host='a.aikllc.tech', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=bb0b4de5961dc7baf37398cc24c45eb7 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1017)')))"
https://0s1tn4.dness.top/api/v1/client/subscribe?token=806af1bab2cc27eb02c2cf9ec1e9f7b9,6,成功,
https://a.qcsub.top/api/v1/client/subscribe?token=17cfd02f981a00311283f76e9303fbce&amp;flag=clash,0,失败,请求失败: 403 Client Error: Forbidden for url: https://panel.qqcjs.top
https://569cdn.1010520.click/api/v1/client/subscribe?token=3bdc20e810ec852986e69a90dd9e1da7,0,失败,请求失败: 403 Client Error: Forbidden for url: https://569cdn.1010520.click/api/v1/client/subscribe?token=3bdc20e810ec852986e69a90dd9e1da7
http://vip.365cloud.me/api/v1/client/subscribe?token=1b361a84a84e233a1f110829ff572436,0,失败,"请求失败: HTTPConnectionPool(host='vip.365cloud.me', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=1b361a84a84e233a1f110829ff572436 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf10400>: Failed to resolve 'vip.365cloud.me' ([Errno -2] Name or service not known)""))"
http://dd.cxld.sbs/api/v1/client/subscribe?token=5e172019e1c5eb1fa49ef546abcc59de,0,失败,"请求失败: HTTPConnectionPool(host='dd.cxld.sbs', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=5e172019e1c5eb1fa49ef546abcc59de (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf115d0>: Failed to resolve 'dd.cxld.sbs' ([Errno -2] Name or service not known)""))"
https://api.x-bai.vip/api/v1/client/subscribe?token=7113360296f8220522a45ace626959a2,0,失败,"请求失败: HTTPSConnectionPool(host='api.x-bai.vip', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=7113360296f8220522a45ace626959a2 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf11720>: Failed to resolve 'api.x-bai.vip' ([Errno -2] Name or service not known)""))"
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=5dab5133e457850cbf99507eb4d687e0,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5dab5133e457850cbf99507eb4d687e0 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://app.legeth.cc/api/v1/client/subscribe?token=c23227340b807bbc974646f39741c143,0,失败,"请求失败: HTTPSConnectionPool(host='app.legeth.cc', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c23227340b807bbc974646f39741c143 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3f6d0>: Failed to resolve 'app.legeth.cc' ([Errno -2] Name or service not known)""))"
https://52daishu.uk/api/v1/client/subscribe?token=7ac825032570a917a24257a04a68568a,39,成功,
https://api.ymvpnpro.cc:8700/7air2vr7ikiqzgvxz/api/v1/client/subscribe?token=a486c097dedef0771b020ea1608f1024,0,失败,内容过短
https://774.gs/CUxUL,0,成功,
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=a4d967de43dd1dabe314e0b43dea2971,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a4d967de43dd1dabe314e0b43dea2971 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://dy.changyouVPN.top/api/v1/client/subscribe?token=95e1bbd6c3d19ff490e2ecbafad071f0,0,失败,内容过短
https://575720.xyz/api/v1/client/subscribe?token=181d308f4ffd2c8997553c1c78fc60bd,0,失败,"请求失败: HTTPSConnectionPool(host='575720.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=181d308f4ffd2c8997553c1c78fc60bd (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf6aad0>: Failed to resolve '575720.xyz' ([Errno -5] No address associated with hostname)""))"
http://mf.kejifan88.top/api/v1/client/subscribe?token=59680bee2655acd51c3582c5c5e1e518,0,失败,"请求失败: HTTPConnectionPool(host='mf.kejifan88.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=59680bee2655acd51c3582c5c5e1e518 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf6ae90>: Failed to resolve 'mf.kejifan88.top' ([Errno -2] Name or service not known)""))"
https://app.ppssqq.com/link/O5DenNePHAGFubRs?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='app.ppssqq.com', port=443): Max retries exceeded with url: /link/O5DenNePHAGFubRs?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf12c20>: Failed to resolve 'app.ppssqq.com' ([Errno -2] Name or service not known)""))"
http://e8a580bd3a51b6050aabd8919a17d106.52pokemon.top/api/v1/client/subscribe?token=8949b177fcce579e75a0f6b1178ea72c,0,失败,"请求失败: HTTPConnectionPool(host='e8a580bd3a51b6050aabd8919a17d106.52pokemon.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8949b177fcce579e75a0f6b1178ea72c (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf12800>: Failed to resolve 'e8a580bd3a51b6050aabd8919a17d106.52pokemon.top' ([Errno -2] Name or service not known)""))"
http://subs.202218.xyz/link/JGkw45anXjwQOhes?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/JGkw45anXjwQOhes?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf6a9e0>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://api.eejsq.org/api/v1/client/subscribe?token=1896c217c2f6292d1270338b40a4eb24,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.ejiasu.net/api/v1/client/subscribe?token=1896c217c2f6292d1270338b40a4eb24
https://app.jisovpn.site/api/v1/client/subscribe?token=5c19518402456f9e1faf61c62100a226,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5c19518402456f9e1faf61c62100a226 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1de70>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
http://csgo3.fask511.cfd:1588/api/v1/client/subscribe?token=79433825d5d6bc51906c5d9d6b68a97e,0,失败,内容过短
http://gbtgurl01.org/api/v1/client/subscribe?token=382aeefac92556ece9266aaf9563b308,0,失败,内容过短
https://amatrixap.com/link/bBRf5fUI0eldTFKV?clash=1,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/bBRf5fUI0eldTFKV?clash=1
https://api.hy2.lol/api/v1/client/subscribe?token=336a097e9e5cee2dcbf83ae1d085954c,0,失败,"请求失败: HTTPSConnectionPool(host='api.hy2.lol', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=336a097e9e5cee2dcbf83ae1d085954c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8fa0>: Failed to resolve 'api.hy2.lol' ([Errno -2] Name or service not known)""))"
https://3.feiniaoyun01.life/api/v1/client/subscribe?token=a2a852fcc2338442c32160e0c6e9247f,0,成功,
https://aaa.us123.icu/api/v1/client/subscribe?token=0a91e46c7e45adf7389eaecd0965efec,0,失败,"请求失败: HTTPSConnectionPool(host='aaa.us123.icu', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=0a91e46c7e45adf7389eaecd0965efec (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3ff40>: Failed to resolve 'aaa.us123.icu' ([Errno -2] Name or service not known)""))"
https://20189999.xyz/api/v1/client/subscribe?token=c06ba5e79a19d7d3b132ca87ccf6d1bb,0,失败,"请求失败: HTTPSConnectionPool(host='20189999.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c06ba5e79a19d7d3b132ca87ccf6d1bb (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf12080>: Failed to resolve '20189999.xyz' ([Errno -5] No address associated with hostname)""))"
https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=cfe7631cc6e89485078d4148422067ef,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=cfe7631cc6e89485078d4148422067ef
https://app.cloudlion.me/api/v1/client/subscribe?token=3d3164aceef39d2809d3bafbde557f4d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=3d3164aceef39d2809d3bafbde557f4d
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=8aa7fae2aa09afef367610b7d1cde3a1,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=8aa7fae2aa09afef367610b7d1cde3a1 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://g3i.buzz/v3/subscr?id=c64d8ba46be149169bb8651d41173901,0,失败,内容过短
http://c9k.buzz/v3/subscr?id=a25a67135d0d47179889908e08db0a98,0,失败,请求失败: 403 Client Error: Forbidden for url: https://c9k.buzz/v3/subscr?id=a25a67135d0d47179889908e08db0a98
http://subs.202218.xyz/link/nZUlZLlZPEZXb1iP?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/nZUlZLlZPEZXb1iP?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3d930>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://api.dingyueapi.win/api/v1/client/subscribe?token=957da09a4850150bf79d584e16f3ca0b,0,失败,内容过短
http://66ds.dishujichang.xyz/sha/bi/gfw?token=6ff1365d967c5862339efc60d6c3aa48,0,失败,请求失败: 403 Client Error: Forbidden for url: http://66ds.dishujichang.xyz/sha/bi/gfw?token=6ff1365d967c5862339efc60d6c3aa48
http://www.freeflyingcloud.xyz/api/v1/client/subscribe?token=ab97fad5d33fd7779a5c34bc27e122b3,0,成功,
https://3k.fxxk.dedyn.io/sub?host=xn--vjqt50blsfzoo1f8a.repe.gay&amp;uuid=ca8692b7-8f6f-4346-a916-c1e9798ab91b,0,失败,"请求失败: HTTPSConnectionPool(host='3k.fxxk.dedyn.io', port=443): Max retries exceeded with url: /sub?host=xn--vjqt50blsfzoo1f8a.repe.gay&amp;uuid=ca8692b7-8f6f-4346-a916-c1e9798ab91b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf6aa10>: Failed to resolve '3k.fxxk.dedyn.io' ([Errno -2] Name or service not known)""))"
http://v2pn.live/api/v1/client/subscribe?token=a186daee159b4cc77257157a6ae5d1a2,0,失败,"请求失败: HTTPConnectionPool(host='v2pn.live', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=a186daee159b4cc77257157a6ae5d1a2 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed8b20>: Failed to resolve 'v2pn.live' ([Errno -2] Name or service not known)""))"
https://8payj.no-mad-world.club/link/eoCDIhsiLhWsCxCE?clash=3&amp;extend=1,0,失败,请求失败: 404 Client Error: Not Found for url: https://8payj.no-mad-world.club/link/eoCDIhsiLhWsCxCE?clash=3&amp;extend=1
http://www.bfyun.top/api/v1/client/subscribe?token=94b541c78f3d2548583d6c4282313051,0,失败,"请求失败: HTTPConnectionPool(host='www.bfyun.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=94b541c78f3d2548583d6c4282313051 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf116f0>: Failed to resolve 'www.bfyun.top' ([Errno -2] Name or service not known)""))"
http://bcast.ink/api/v1/client/subscribe?token=5fa9280a5f5783ee493d3a9f9019ef3f,0,失败,"请求失败: HTTPConnectionPool(host='bcast.ink', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=5fa9280a5f5783ee493d3a9f9019ef3f (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf839d0>: Failed to resolve 'bcast.ink' ([Errno -2] Name or service not known)""))"
https://api.xqc.best/api/v1/client/subscribe?token=8f8265b9122af6234cb00d136beb282f,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=8f8265b9122af6234cb00d136beb282f (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://774.gs/frSai,0,成功,
http://s.33y.run/v3/subscr?id=e3dd1fbb06ad44678e02bb8e9287ffa8,0,失败,请求失败: 403 Client Error: Forbidden for url: https://s.33y.run/v3/subscr?id=e3dd1fbb06ad44678e02bb8e9287ffa8
http://s.33y.run/v3/subscr?id=d2b1dfb137514b62b2c2cc234a15adb7,0,失败,请求失败: 403 Client Error: Forbidden for url: https://s.33y.run/v3/subscr?id=d2b1dfb137514b62b2c2cc234a15adb7
http://qiancheng.ml/,0,失败,"请求失败: HTTPConnectionPool(host='qiancheng.ml', port=80): Max retries exceeded with url: / (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf69bd0>: Failed to resolve 'qiancheng.ml' ([Errno -2] Name or service not known)""))"
https://api.sub-100.one/link/F0hqrteMMLRKnCzA?sub=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.sub-100.one/link/F0hqrteMMLRKnCzA?sub=3
https://888.868988.xyz/api/v1/client/subscribe?token=c85cda7d21fa99f8a0aacc2cbc28806b,0,失败,"请求失败: HTTPSConnectionPool(host='888.868988.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c85cda7d21fa99f8a0aacc2cbc28806b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1e740>: Failed to resolve '888.868988.xyz' ([Errno -2] Name or service not known)""))"
https://569cdn.1010520.click/api/v1/client/subscribe?token=23268a6346f9926daed8bb3455051193&amp;flag=meta,0,失败,请求失败: 403 Client Error: Forbidden for url: https://569cdn.1010520.click/api/v1/client/subscribe?token=23268a6346f9926daed8bb3455051193&amp;flag=meta
https://6-8xn.pages.dev/sub/d342d11e-d424-4583-b36e-524ab1f0afa4,0,失败,"请求失败: HTTPSConnectionPool(host='6-8xn.pages.dev', port=443): Max retries exceeded with url: /sub/d342d11e-d424-4583-b36e-524ab1f0afa4 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1e260>: Failed to resolve '6-8xn.pages.dev' ([Errno -3] Temporary failure in name resolution)""))"
https://99ding.men/api/v1/client/subscribe?token=ae45fff78188e0cc15cb29b1b4eaa111,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=ae45fff78188e0cc15cb29b1b4eaa111
http://sp.nfsq.me/api/v1/client/subscribe?token=4f788e9df4d02e57157edb61fadc6b93,0,成功,
http://gbtgurl01.org/api/v1/client/subscribe?token=1c47812d11cffb1508b2bc090bc8620c,0,失败,内容过短
https://1.bethebest.eu.org/api/v1/client/subscribe?token=ef027a5bfc788a6b7eddcc859a078b14,0,失败,内容过短
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=b56b25ed0dec93af61fa7a81f6b840fe,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=b56b25ed0dec93af61fa7a81f6b840fe
https://99ding.men/api/v1/client/subscribe?token=e756c8c4234cb0650e59f78c45fcf5f4,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=e756c8c4234cb0650e59f78c45fcf5f4
https://4e60bafd-0633-4e8d-a02a-eef51cd1ad8e.xn--mes358a.art/api/v1/client/subscribe?token=be9dc73e711bcc98bcb808eea57c7cac,0,失败,"请求失败: HTTPSConnectionPool(host='4e60bafd-0633-4e8d-a02a-eef51cd1ad8e.xn--mes358a.art', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=be9dc73e711bcc98bcb808eea57c7cac (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8400>: Failed to resolve '4e60bafd-0633-4e8d-a02a-eef51cd1ad8e.xn--mes358a.art' ([Errno -2] Name or service not known)""))"
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;flag=clash,0,成功,
https://a.qcsub.top/api/v1/client/subscribe?token=17cfd02f981a00311283f76e9303fbce,0,失败,请求失败: 403 Client Error: Forbidden for url: https://panel.qqcjs.top
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=34f923281be9433b2de5b1aebbbce5d6,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=34f923281be9433b2de5b1aebbbce5d6
http://ant77.top/api/v1/client/subscribe?token=d580223a12d39508006e655dbc34b0fa,0,失败,"请求失败: HTTPConnectionPool(host='ant77.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=d580223a12d39508006e655dbc34b0fa (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf685b0>: Failed to resolve 'ant77.top' ([Errno -2] Name or service not known)""))"
https://a.kuaicloud.xyz/link/95thpJiCV9OBD93c?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/95thpJiCV9OBD93c?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa0940>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://99ding.men/api/v1/client/subscribe?token=0fa8699ab2414c8f6d6c31350622d305&amp;flag=clash,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=0fa8699ab2414c8f6d6c31350622d305&amp;flag=clash
http://cdn1.ispisp.tk/api/v1/client/subscribe?token=0b87fe27c9116abe49402d218fb096ff,0,失败,"请求失败: HTTPConnectionPool(host='cdn1.ispisp.tk', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=0b87fe27c9116abe49402d218fb096ff (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf83550>: Failed to resolve 'cdn1.ispisp.tk' ([Errno -2] Name or service not known)""))"
https://api.sub-100.one/link/E62LIYdf4u2hePJM?sub=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.sub-100.one/link/E62LIYdf4u2hePJM?sub=3
https://99ding.men/api/v1/client/subscribe?token=0fa8699ab2414c8f6d6c31350622d305,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=0fa8699ab2414c8f6d6c31350622d305
http://dy.changyouVPN.top/api/v1/client/subscribe?token=ea8146316de50ab1d7015f8d68c9df42,0,失败,内容过短
https://123x6y9z.d01olikp.thesyeec7l60ouav1lz0tesk.top/api/v1/client/subscribe?token=73c03afaea47a651a0ad909f5b4b2029,0,失败,"请求失败: HTTPSConnectionPool(host='123x6y9z.d01olikp.thesyeec7l60ouav1lz0tesk.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=73c03afaea47a651a0ad909f5b4b2029 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3e0e0>: Failed to resolve '123x6y9z.d01olikp.thesyeec7l60ouav1lz0tesk.top' ([Errno -2] Name or service not known)""))"
http://panda.xn--lbrx91akmhm30c.com/api/v1/client/subscribe?token=5e7411e883e5afc2a81cc272fc0c6898,0,失败,"请求失败: HTTPConnectionPool(host='panda.xn--lbrx91akmhm30c.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=5e7411e883e5afc2a81cc272fc0c6898 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed8be0>: Failed to resolve 'panda.xn--lbrx91akmhm30c.com' ([Errno -2] Name or service not known)""))"
https://99ding.men/api/v1/client/subscribe?token=ce03f27bbce8c076d0f43e12c45b1fa5,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=ce03f27bbce8c076d0f43e12c45b1fa5
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=212ecbd29bd748f22df31f79c6ac2582,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=212ecbd29bd748f22df31f79c6ac2582
https://68123106-3e43-4958-b75a-b06e81eabf79.50d88e28-a870-497d-bf87-c20fb6802871.camdvr.org/trojan-6qo.pages.dev/95b?clash,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://68123106-3e43-4958-b75a-b06e81eabf79.50d88e28-a870-497d-bf87-c20fb6802871.camdvr.org/trojan-6qo.pages.dev/95b?clash
https://api.662289.xyz/api/v1/client/subscribe?token=3c8d0133fecfcebb8e3437b7e718e9ee,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.662289.xyz/api/v1/client/subscribe?token=3c8d0133fecfcebb8e3437b7e718e9ee
https://888.868988.xyz/api/v1/client/subscribe?token=64f879f0c817248c9ff1ce4eadec535c,0,失败,"请求失败: HTTPSConnectionPool(host='888.868988.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=64f879f0c817248c9ff1ce4eadec535c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa1c00>: Failed to resolve '888.868988.xyz' ([Errno -2] Name or service not known)""))"
https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=55829eb8e25c26ae742e5f54cd68dcb6,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=55829eb8e25c26ae742e5f54cd68dcb6
https://445600.ml/yunbaitechnodes,0,失败,"请求失败: HTTPSConnectionPool(host='445600.ml', port=443): Max retries exceeded with url: /yunbaitechnodes (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa2620>: Failed to resolve '445600.ml' ([Errno -2] Name or service not known)""))"
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=f0858ff0a06e3e5c377ab69522abc04d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=f0858ff0a06e3e5c377ab69522abc04d
http://panda.xn--lbrx91akmhm30c.com/api/v1/client/subscribe?token=e1b1bc8f674e1be01470a224580a96a0,0,失败,"请求失败: HTTPConnectionPool(host='panda.xn--lbrx91akmhm30c.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=e1b1bc8f674e1be01470a224580a96a0 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3f0a0>: Failed to resolve 'panda.xn--lbrx91akmhm30c.com' ([Errno -2] Name or service not known)""))"
https://anft4s.cluobotu.xyz/api/v1/client/subscribe?token=8dd1ac6ebbad08764e2514382043ed1b,6,成功,
https://4iwg7p.babaivip.top/api/v1/client/subscribe?token=0631b0e70e123fd5c1bb9ff2bff2cda6,5,成功,
https://353g78qgfq.surfcat.store/api/v1/client/subscribe?token=8b8d3ad15a6da23c6f534cc947487247,0,失败,请求失败: 526 Server Error: <none> for url: https://353g78qgfq.surfcat.store/api/v1/client/subscribe?token=8b8d3ad15a6da23c6f534cc947487247
https://4j99dr.babaivip.top/api/v1/client/subscribe?token=0631b0e70e123fd5c1bb9ff2bff2cda6,5,成功,
https://231787.xyz/api/v1/client/subscribe?token=94bd95d4b08522710e77047d8a14a21e,0,失败,内容过短
http://dydz.xn--mesv8bx6xtx3b.com:2006/api/v1/client/subscribe?token=e6763082d153dd317990382143d7b34f&amp;flag=meta,0,失败,"请求失败: HTTPConnectionPool(host='dydz.xn--mesv8bx6xtx3b.com', port=2006): Max retries exceeded with url: /api/v1/client/subscribe?token=e6763082d153dd317990382143d7b34f&amp;flag=meta (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf80be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://a.pikachu.cyou/api/v1/client/subscribe?token=d83de9fb1ffef52c58dcd3dbb672fb31,0,失败,"请求失败: HTTPSConnectionPool(host='a.pikachu.cyou', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d83de9fb1ffef52c58dcd3dbb672fb31 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa3910>: Failed to resolve 'a.pikachu.cyou' ([Errno -2] Name or service not known)""))"
https://569cdn.1010520.click/api/v1/client/subscribe?token=23268a6346f9926daed8bb3455051193,0,失败,请求失败: 403 Client Error: Forbidden for url: https://569cdn.1010520.click/api/v1/client/subscribe?token=23268a6346f9926daed8bb3455051193
https://52.xiaoyangrenml.top/api/v1/client/subscribe?token=38d5380b510bff821cff132347c0f55a&amp;flag=clash,0,失败,"请求失败: HTTPSConnectionPool(host='52.xiaoyangrenml.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=38d5380b510bff821cff132347c0f55a&amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3d510>: Failed to resolve '52.xiaoyangrenml.top' ([Errno -2] Name or service not known)""))"
http://www.moguyun.xyz/api/v1/client/subscribe?token=33f9ce0707ba11aa170a1b9a1e20f371,0,成功,
https://1.bethebest.eu.org/api/v1/client/subscribe?token=3715a07dc448ad9f275aa73e54b762b7&amp;types=vmess,0,失败,请求失败: 403 Client Error: Forbidden for url: https://1.bethebest.eu.org/api/v1/client/subscribe?token=3715a07dc448ad9f275aa73e54b762b7&amp;types=vmess
https://amatrixap.com/link/04wpfAmdassDF1e6?clash=1,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/04wpfAmdassDF1e6?clash=1
http://s3.subcsyun.online/api/v1/client/subscribe?token=ad8995f33722feef0d16e3bcb7c2dd8b,0,成功,
https://api.ikuuu.science/link/CzuDOnMyyGBiyttK?sub=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.ikuuu.science/link/CzuDOnMyyGBiyttK?sub=3
https://30178aeb-8299-045d-fb67-ae12ce73dd2c.buou.lol/api/buou?token=bdb238d5118a0f60589b1c581b7e558b,0,失败,"请求失败: HTTPSConnectionPool(host='30178aeb-8299-045d-fb67-ae12ce73dd2c.buou.lol', port=443): Max retries exceeded with url: /api/buou?token=bdb238d5118a0f60589b1c581b7e558b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa0fd0>: Failed to resolve '30178aeb-8299-045d-fb67-ae12ce73dd2c.buou.lol' ([Errno -2] Name or service not known)""))"
http://api.mnhhnbb.com/api/v1/client/subscribe?token=c2e45925c513936a01c468b066861e44,0,失败,请求失败: 404 Client Error: Not Found for url: http://api.mnhhnbb.com/api/v1/client/subscribe?token=c2e45925c513936a01c468b066861e44
http://s1.subcsyun.online/api/v1/client/subscribe?token=3db954d678fed76fd2b82700890c077d,0,成功,
https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=0ed5935e0aa103f4a133d2e6a2f75701,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=0ed5935e0aa103f4a133d2e6a2f75701
https://api.qiduo.eu.org/link/J924bQtE4xveVBme?sub=3,0,失败,"请求失败: HTTPSConnectionPool(host='api.qiduo.eu.org', port=443): Max retries exceeded with url: /link/J924bQtE4xveVBme?sub=3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3c580>: Failed to resolve 'api.qiduo.eu.org' ([Errno -3] Temporary failure in name resolution)""))"
https://a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz/api/v1/client/subscribe?token=9b6a835f61c9d98378917183621df470,0,失败,"请求失败: HTTPSConnectionPool(host='a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=9b6a835f61c9d98378917183621df470 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1dff0>: Failed to resolve 'a429f925-f4ea-4faf-92df-cb3a833e05e8.eevpn.xyz' ([Errno -2] Name or service not known)""))"
http://guolicheng.windowsupdate.lol/api/v1/client/subscribe?token=70191de2b352389b2ef2fa59ce9b98e1,0,成功,
https://apidy.pqjc.site/api/v1/client/subscribe?token=fe7d7becdfabb58c81b41d46b158d4a0,0,失败,请求失败: 403 Client Error: Forbidden for url: https://apidy.pqjc.site/api/v1/client/subscribe?token=fe7d7becdfabb58c81b41d46b158d4a0
https://api-hx.02000.net/api/v1/client/subscribe?token=9f44dff9e7a82425fc71e78c9d79fbb1,78,成功,
https://api.tshl.cc/link/9M6w2o27KoaXKzlc?mu=6,0,失败,内容过短
https://api.ssrsub.com/api/v1/client/subscribe?token=31cf50bb67f27e40ab48132723b2ae19,0,失败,内容过短
https://app.jisovpn.site/api/v1/client/subscribe?token=3e483a7b7f0caaca3fa8a947495b0d92,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3e483a7b7f0caaca3fa8a947495b0d92 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf82290>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
https://air.tuanzi.gq/sub.yaml,0,失败,"请求失败: HTTPSConnectionPool(host='air.tuanzi.gq', port=443): Max retries exceeded with url: /sub.yaml (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed86a0>: Failed to resolve 'air.tuanzi.gq' ([Errno -2] Name or service not known)""))"
https://api.meomiao.me/api/v1/client/subscribe?token=8d04dce911b9fdf8dd4ade86ad7e5ac7,0,失败,"请求失败: HTTPSConnectionPool(host='api.meomiao.me', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=8d04dce911b9fdf8dd4ade86ad7e5ac7 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf83370>: Failed to resolve 'api.meomiao.me' ([Errno -2] Name or service not known)""))"
https://api.1vpn.sbs/api/v1/client/subscribe?token=666e3e7537a709448e495688006a0684,0,失败,"请求失败: HTTPSConnectionPool(host='api.1vpn.sbs', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=666e3e7537a709448e495688006a0684 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf68640>: Failed to resolve 'api.1vpn.sbs' ([Errno -3] Temporary failure in name resolution)""))"
https://0d2th.no-mad-world.club/link/dacqbivsqysnpzlq?clash=3&amp;extend=1,7,成功,
https://41be350f-5079-4195-8329-f6fa25f9906a.com/api/v1/client/subscribe?token=d5bc5b1562065956bb86bcbb6258d4d8,0,失败,"请求失败: HTTPSConnectionPool(host='41be350f-5079-4195-8329-f6fa25f9906a.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d5bc5b1562065956bb86bcbb6258d4d8 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec9f30>: Failed to resolve '41be350f-5079-4195-8329-f6fa25f9906a.com' ([Errno -2] Name or service not known)""))"
https://aoop.top/api/v1/client/subscribe?token=05fa38c9733e99a56091b2d750a90c9e,0,失败,请求失败: 403 Client Error: Forbidden for url: https://aoop.top/api/v1/client/subscribe?token=05fa38c9733e99a56091b2d750a90c9e
https://209966.xyz/link/hfh5s7z26gi9pamu?sub=3,0,失败,"请求失败: HTTPSConnectionPool(host='209966.xyz', port=443): Max retries exceeded with url: /link/hfh5s7z26gi9pamu?sub=3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec87f0>: Failed to resolve '209966.xyz' ([Errno -5] No address associated with hostname)""))"
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=87ac36beeb72ab1d00e20ea4646f7a93,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=87ac36beeb72ab1d00e20ea4646f7a93 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://dd.cxld.sbs/api/v1/client/subscribe?token=3bb709ab3eb3460f1182b5ecb7bf57b9,0,失败,"请求失败: HTTPConnectionPool(host='dd.cxld.sbs', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=3bb709ab3eb3460f1182b5ecb7bf57b9 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecbbe0>: Failed to resolve 'dd.cxld.sbs' ([Errno -2] Name or service not known)""))"
https://api.liltjay.ip-ddns.com/TQWMYCWH2D,16,成功,
https://353g78qgfq.surfcat.store/api/v1/client/subscribe?token=aea5fd520527f8cd4ad458819e588e57,0,失败,请求失败: 526 Server Error: <none> for url: https://353g78qgfq.surfcat.store/api/v1/client/subscribe?token=aea5fd520527f8cd4ad458819e588e57
https://a.aikllc.tech/api/v1/client/subscribe?token=1d03e8c5adba1d5e1a87e74da64c122d,0,失败,"请求失败: HTTPSConnectionPool(host='a.aikllc.tech', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=1d03e8c5adba1d5e1a87e74da64c122d (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1017)')))"
https://52pokemon.xz61.cn/api/v1/client/subscribe?token=22aa64863d5172710f15d68b28223621,0,失败,请求失败: 403 Client Error: Forbidden for url: https://52pokemon.xz61.cn/api/v1/client/subscribe?token=22aa64863d5172710f15d68b28223621
http://guanxi.cloudns.be:8000/sub/v2ray/6IOh5qGD5LqRIDEwMFTvvIjlhqDluIzvvIk%3D,0,失败,"请求失败: HTTPConnectionPool(host='guanxi.cloudns.be', port=8000): Max retries exceeded with url: /sub/v2ray/6IOh5qGD5LqRIDEwMFTvvIjlhqDluIzvvIk%3D (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8ec8250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://abc.xn--8lt534m.ml/api/temp,0,失败,"请求失败: HTTPSConnectionPool(host='abc.xn--8lt534m.ml', port=443): Max retries exceeded with url: /api/temp (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec9b10>: Failed to resolve 'abc.xn--8lt534m.ml' ([Errno -2] Name or service not known)""))"
https://666119.xyz/link/7oIuIUE2onn18Hd6?clash=1,0,失败,请求失败: 403 Client Error: Forbidden for url: https://666119.xyz/link/7oIuIUE2onn18Hd6?clash=1
https://a.qcsub.com/api/v1/client/subscribe?token=9741cc6cd8ae29bc83d9338fc23a362d,0,失败,"请求失败: HTTPSConnectionPool(host='a.qcsub.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=9741cc6cd8ae29bc83d9338fc23a362d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecb040>: Failed to resolve 'a.qcsub.com' ([Errno -2] Name or service not known)""))"
https://ac1f3b35-1d03-3a85-beab-258d8f23edc6.nginxdotu.xyz/link/kKmQMz7wmFbOlOuz?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='ac1f3b35-1d03-3a85-beab-258d8f23edc6.nginxdotu.xyz', port=443): Max retries exceeded with url: /link/kKmQMz7wmFbOlOuz?clash=1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1017)')))"
http://subs.202218.xyz/link/tT9Av5hJyvffyT0w?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/tT9Av5hJyvffyT0w?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecaef0>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://47.237.21.85/api/v1/client/subscribe?token=f90ee423b00b2d456ceae30c9781c424,0,失败,内容过短
http://188.213.196.100:8585/vmess/sub,0,失败,"请求失败: HTTPConnectionPool(host='188.213.196.100', port=8585): Max retries exceeded with url: /vmess/sub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8ecae00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://a.suixincloud.top/api/v1/client/subscribe?token=a8f76ddb6b949a70d34150b1f3cb8dc9,0,失败,"请求失败: HTTPSConnectionPool(host='a.suixincloud.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a8f76ddb6b949a70d34150b1f3cb8dc9 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfb4640>: Failed to resolve 'a.suixincloud.top' ([Errno -3] Temporary failure in name resolution)""))"
http://guolicheng.windowsupdate.lol/api/v1/client/subscribe?token=c2f14863ca9004ee6f77be311f36e942,0,成功,
https://api.orangeapi.org/sub?suburl=https%3A%2F%2Fmuguacloud.top%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D43ed0719adbcdc886772e5caecbfe545&amp;newhost=a.189.cn&amp;showhost=true,0,失败,"请求失败: HTTPSConnectionPool(host='api.orangeapi.org', port=443): Max retries exceeded with url: /sub?suburl=https%3A%2F%2Fmuguacloud.top%2Fapi%2Fv1%2Fclient%2Fsubscribe%3Ftoken%3D43ed0719adbcdc886772e5caecbfe545&amp;newhost=a.189.cn&amp;showhost=true (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1017)')))"
https://apps.apple.com/app/id6451272673,0,失败,请求失败: 404 Client Error: Not Found for url: https://apps.apple.com/app/id6451272673
https://api.abyssyun.top/api/v1/client/subscribe?token=83e18798880e917220bdbed3afff2919,0,成功,
http://www.feiyun.club/api/v1/client/subscribe?token=04a1562ae9e1934ac061ce05312d92ff,0,失败,"请求失败: HTTPConnectionPool(host='www.feiyun.club', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=04a1562ae9e1934ac061ce05312d92ff (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ec9cf0>: Failed to resolve 'www.feiyun.club' ([Errno -2] Name or service not known)""))"
http://xxxu.xyz/api/v1/client/subscribe?token=b92fe0216c5211dbb5660af864eb9a85,0,失败,"请求失败: HTTPConnectionPool(host='xxxu.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=b92fe0216c5211dbb5660af864eb9a85 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4cb16bd00>: Failed to resolve 'xxxu.xyz' ([Errno -2] Name or service not known)""))"
https://52pokemon.xz61.cn/api/v1/client/subscribe?token=9e40db08b7e09b7471c99b89c4c3d7d6,0,失败,内容过短
https://api2.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=afc10da32cc774b8e72ee887d1edf7a5,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api2.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=afc10da32cc774b8e72ee887d1edf7a5
http://subs.202218.xyz/link/koapzwIST5jhjMAE?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/koapzwIST5jhjMAE?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecbc40>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://2381bfde-8c93-4701-8f14-24f071067a1a.nginx24bit.xyz/api/v1/client/subscribe?token=7a34a7e4d092c4bc11064c4ca594a15c,45,成功,
http://35.241.103.103/api/v1/client/subscribe?token=ffb6dceb832b8678e744a734c5fed7d2,0,失败,请求超时
http://s.33y.run/v3/subscr?id=cb971d1363e54209a70efbce92ce41ef,0,失败,请求失败: 403 Client Error: Forbidden for url: https://s.33y.run/v3/subscr?id=cb971d1363e54209a70efbce92ce41ef
http://www.freeflyingcloud.xyz/api/v1/client/subscribe?token=3af0fc28a300c9ebc6544504f18d9f82,0,成功,
https://a.kuaicloud.xyz/link/A7NWy6nM6LpI6tGM?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/A7NWy6nM6LpI6tGM?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec95d0>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://api.fuckyun.cc/api/v1/client/subscribe?token=409f2a1348dc8de0d4e9d71c63054c51,0,失败,请求失败: 530 Server Error: <none> for url: https://api.fuckyun.cc/api/v1/client/subscribe?token=409f2a1348dc8de0d4e9d71c63054c51
http://1.1598888.xyz/api/v1/client/subscribe?token=e2c8421cd8543cd904f255fbef4490cd#subscribe?token=e2c8421cd8543cd904f255fbef4490cd,0,失败,请求超时
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;flag=v2ray,0,成功,
http://s.kalaa.me/v3/subscr?id=4022f6b4ab7341479a00ff0b4c4a09cb,0,失败,"请求失败: HTTPConnectionPool(host='s.kalaa.me', port=80): Max retries exceeded with url: /v3/subscr?id=4022f6b4ab7341479a00ff0b4c4a09cb (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecbd90>: Failed to resolve 's.kalaa.me' ([Errno -2] Name or service not known)""))"
http://shoujiyanxishe.tk/link/HhpyDmTLhKXbtC00?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='shoujiyanxishe.tk', port=80): Max retries exceeded with url: /link/HhpyDmTLhKXbtC00?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8eca890>: Failed to resolve 'shoujiyanxishe.tk' ([Errno -2] Name or service not known)""))"
http://37.32.27.116:8080/sip002/sub,0,失败,请求超时
http://sub.xn--4gq62f8yih87b.xyz/yiyuan?token=5bf793860e66201495506e754b77a959&amp;flag=meta#yiyuan?token=5bf793860e66201495506e754b77a959&amp;flag=meta,0,失败,"请求失败: HTTPConnectionPool(host='sub.xn--4gq62f8yih87b.xyz', port=80): Max retries exceeded with url: /yiyuan?token=5bf793860e66201495506e754b77a959&amp;flag=meta (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8d1e290>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
https://7cd49968.nmsubs.com/api/v1/client/subscribe?token=306de9846288d80c11bab91be149edfa,0,失败,"请求失败: HTTPSConnectionPool(host='7cd49968.nmsubs.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=306de9846288d80c11bab91be149edfa (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecbe20>: Failed to resolve '7cd49968.nmsubs.com' ([Errno -2] Name or service not known)""))"
http://nekox.eu5.org/new.txt,0,成功,
http://6465307854ab0a2c82b66d32ffa2107e.52pokemon.top/api/v1/client/subscribe?token=8bae25c486e76f8dd12166c3dd33e6a4&amp;flag=ClashMeta,0,失败,"请求失败: HTTPConnectionPool(host='6465307854ab0a2c82b66d32ffa2107e.52pokemon.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8bae25c486e76f8dd12166c3dd33e6a4&amp;flag=ClashMeta (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecce50>: Failed to resolve '6465307854ab0a2c82b66d32ffa2107e.52pokemon.top' ([Errno -2] Name or service not known)""))"
https://api.fuckyun.cc/api/v1/client/subscribe?token=e791ab84befa90ee50443bea41a75a68,0,失败,请求失败: 530 Server Error: <none> for url: https://api.fuckyun.cc/api/v1/client/subscribe?token=e791ab84befa90ee50443bea41a75a68
https://ae86.235999.xyz/api/v1/client/subscribe?token=5212731fb930a0ea589c829af7dd7a81,0,失败,"请求失败: HTTPSConnectionPool(host='ae86.235999.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5212731fb930a0ea589c829af7dd7a81 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecc040>: Failed to resolve 'ae86.235999.xyz' ([Errno -2] Name or service not known)""))"
https://520748.xyz/api/v1/client/subscribe?token=e01526639ba89fde7f69b75e31a5f1c1,0,失败,"请求失败: HTTPSConnectionPool(host='520748.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e01526639ba89fde7f69b75e31a5f1c1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecbd30>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
http://www.freeflyingcloud.xyz/api/v1/client/subscribe?token=3de6c51e6ec0b20a21254529d9b3f800,0,成功,
http://subs.202218.xyz/link/kIpLZPoApoqJYKzm?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/kIpLZPoApoqJYKzm?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecb100>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://api.ktcat.online/ktcat?token=2cc26c1a876569ac0f0fe1a07c92e769,0,失败,"请求失败: HTTPSConnectionPool(host='api.ktcat.online', port=443): Max retries exceeded with url: /ktcat?token=2cc26c1a876569ac0f0fe1a07c92e769 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecfb20>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
http://s4.subcsyun.online/api/v1/client/subscribe?token=9ed73fe3e6c60bba9ba5f3d7fb9a9049,0,成功,
https://api.sanfen013.xyz/api/v1/client/subscribe?token=c44789dd35768f750aef3b9d6fb6510e,0,失败,"请求失败: HTTPSConnectionPool(host='api.sanfen013.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c44789dd35768f750aef3b9d6fb6510e (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecd0f0>: Failed to resolve 'api.sanfen013.xyz' ([Errno -2] Name or service not known)""))"
http://108.60.201.16/v4/GLOBE/ACT,0,失败,请求超时
https://api.ssrsub.com/api/v1/client/subscribe?token=22c168a0eb606bdd60c7530f152e15b0,0,失败,内容过短
https://api.eejsq.org/api/v1/client/subscribe?token=8f4e36db7a6584eb0805e35c8aadeac3,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.ejiasu.net/api/v1/client/subscribe?token=8f4e36db7a6584eb0805e35c8aadeac3
https://api3.6yuan.top/api/v1/client/subscribe?token=d1bdb8257abebbcfec16e2f874123138,0,失败,"请求失败: HTTPSConnectionPool(host='api3.6yuan.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d1bdb8257abebbcfec16e2f874123138 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecbe80>: Failed to resolve 'api3.6yuan.top' ([Errno -2] Name or service not known)""))"
http://tg.cyy200.xyz/api/v1/client/subscribe?token=1aea754676fb9bbcafceb84e7df96735,0,失败,"请求失败: HTTPConnectionPool(host='tg.cyy200.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=1aea754676fb9bbcafceb84e7df96735 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ecd090>: Failed to resolve 'tg.cyy200.xyz' ([Errno -2] Name or service not known)""))"
https://3b0795de.ghelper.me/subs/clash/a3cc8e4405d64a1b6d598e8283d5b54a,0,失败,请求失败: 403 Client Error: Forbidden for url: https://3b0795de.ghelper.me/subs/clash/a3cc8e4405d64a1b6d598e8283d5b54a
http://sub.966888.xyz/api/v1/client/subscribe?token=2d9f235fd8bfb44861f16fb14aed4b0d,15,成功,
http://panda.xn--lbrx91akmhm30c.com/api/v1/client/subscribe?token=6892941e8632a55d0b109203532f29a6,0,失败,"请求失败: HTTPConnectionPool(host='panda.xn--lbrx91akmhm30c.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=6892941e8632a55d0b109203532f29a6 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ec9ea0>: Failed to resolve 'panda.xn--lbrx91akmhm30c.com' ([Errno -2] Name or service not known)""))"
https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=7e891a8671f49a61ece23064e98f9362&amp;flag=clashmeta,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=7e891a8671f49a61ece23064e98f9362&amp;flag=clashmeta
https://1122331.xyz/link/a2rvbgltrzr5naf4?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='1122331.xyz', port=443): Max retries exceeded with url: /link/a2rvbgltrzr5naf4?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecc100>: Failed to resolve '1122331.xyz' ([Errno -5] No address associated with hostname)""))"
http://n15uvht4r659107p.eastasia.cloudapp.azure.com/queue/list?token=40c55cc7caba14930d459adfdc70735c,0,失败,"请求失败: HTTPConnectionPool(host='n15uvht4r659107p.eastasia.cloudapp.azure.com', port=80): Max retries exceeded with url: /queue/list?token=40c55cc7caba14930d459adfdc70735c (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbfcc670>: Failed to resolve 'n15uvht4r659107p.eastasia.cloudapp.azure.com' ([Errno -2] Name or service not known)""))"
https://38.181.25.67/api/v1/client/subscribe?token=9fbba2d5e199b0a8fb1fb3f27538c3e4,0,失败,请求超时
https://api.xinyo.vip/api/v1/client/subscribe?token=825684aa7107efeabe525c12bd10bd02,2,成功,
https://ac59a7cd-11af-3e35-a098-b785688ec627.aliyunsub.com/link/1DswsoSCjJpogBnA?sub=3&amp;extend=1,0,失败,内容过短
https://api.fanss.vip/link/HsszgxYX4oQolvvB?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='api.fanss.vip', port=443): Max retries exceeded with url: /link/HsszgxYX4oQolvvB?clash=1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec9990>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://108.60.201.16/V9/Oder/NCB,0,失败,请求超时
http://ly.ccwink.cc/api/v1/client/subscribe?token=74faf7ece2277eb094d5709e05ca1986,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ly.ccwink.cc/api/v1/client/subscribe?token=74faf7ece2277eb094d5709e05ca1986
http://dishujichang.xyz/api/v1/client/subscribe?token=6b21c7b1788c1c179bbeadc7ba40b001,0,失败,请求失败: 403 Client Error: Forbidden for url: http://dishujichang.xyz/api/v1/client/subscribe?token=6b21c7b1788c1c179bbeadc7ba40b001
https://1g.gay/?v2b=www.ckcloud.cc,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=www.ckcloud.cc (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ec8b20>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=91dd72d46abe213c2ed6bbbeaf2ffa87,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=91dd72d46abe213c2ed6bbbeaf2ffa87
https://9ddea9039d074ed4.cdn.jiashule.com/api/v1/client/subscribe?token=3945fa4c213a81c2ff35f242691f40ba,0,失败,"请求失败: HTTPSConnectionPool(host='9ddea9039d074ed4.cdn.jiashule.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3945fa4c213a81c2ff35f242691f40ba (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ecd630>: Failed to resolve '9ddea9039d074ed4.cdn.jiashule.com' ([Errno -5] No address associated with hostname)""))"
http://www.fanqiang88.top/fanqiang88?token=29c584386a795b163c00cf3c21f0be58,0,失败,请求失败: 404 Client Error: Not Found for url: http://www.fanqiang88.top/fanqiang88?token=29c584386a795b163c00cf3c21f0be58
http://g3.03184.com:8091/F_20241011160900vrqpbf/111.txt,84,成功,
https://a.jiedianxielou.workers.dev/api/v1/client/subscribe?token=UjBGOXVrdFBKYzlqdnBCdThOZUx1b2xoT1loVW41MU0vbDFzbTl5ZmdUN2JqUkJNVW5wT3BuU2hZWTdPMGdmN28wRmN2enExMjR0ejBTU0gvZVllQ1RLWkhRVHpyN0tIV2kyMjBpNGdNQT09,7,成功,
http://37.32.27.116:8080/trojan/sub,0,失败,请求超时
http://py.kjol.cc/tube?id=1,0,失败,"请求失败: HTTPConnectionPool(host='py.kjol.cc', port=80): Max retries exceeded with url: /tube?id=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea8640>: Failed to resolve 'py.kjol.cc' ([Errno -2] Name or service not known)""))"
http://hpyjc.top/api/v1/client/subscribe?token=8eba1d79f60c7e699cc0ce771b68a2c4,0,成功,
https://1.seagullsdream.xyz/api/v1/client/subscribe?token=9b1669170fe9d3d26d5ffd2f379f65d2,0,失败,"请求失败: HTTPSConnectionPool(host='1.seagullsdream.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=9b1669170fe9d3d26d5ffd2f379f65d2 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d085e0>: Failed to resolve '1.seagullsdream.xyz' ([Errno -2] Name or service not known)""))"
http://lianjiasub.work/api/v1/client/subscribe?token=9e7cf936b44e3bd81fe8854449e4fe79,0,失败,请求失败: 403 Client Error: Forbidden for url: http://lianjiasub.work/api/v1/client/subscribe?token=9e7cf936b44e3bd81fe8854449e4fe79
https://25054128.xyz/api/v1/client/subscribe?token=7723b391e7c3c9df9d33816752360cc6,0,失败,请求失败: 403 Client Error: Forbidden for url: https://25054128.xyz/api/v1/client/subscribe?token=7723b391e7c3c9df9d33816752360cc6
http://v1.vmess.top/api/v1/client/subscribe?token=6f3c11c2754281bfffca5e4e9ad50a5b,0,失败,"请求失败: HTTPConnectionPool(host='v1.vmess.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=6f3c11c2754281bfffca5e4e9ad50a5b (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d0a110>: Failed to resolve 'v1.vmess.top' ([Errno -2] Name or service not known)""))"
https://api.eejsq.org/api/v1/client/subscribe?token=1f4094d66350a89050c4accb0ca06535,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.ejiasu.net/api/v1/client/subscribe?token=1f4094d66350a89050c4accb0ca06535
https://airport.rabbitfish.now.cc/sub/948524fd059297ad/clash,0,失败,"请求失败: HTTPSConnectionPool(host='airport.rabbitfish.now.cc', port=443): Max retries exceeded with url: /sub/948524fd059297ad/clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea9c90>: Failed to resolve 'airport.rabbitfish.now.cc' ([Errno -2] Name or service not known)""))"
http://xyyjc.top/api/v1/client/subscribe?token=5a9aa7daa62077d36af9cdf635bb4e6f,0,成功,
https://api.otcopusvpn.cc:18008/subclient/subscribe?token=03deb7b786711282ee98acc03d2fa23f,0,成功,
https://app.legeth.cc/api/v1/client/subscribe?token=f1706eac264471b041a29774f43fb25b,0,失败,"请求失败: HTTPSConnectionPool(host='app.legeth.cc', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f1706eac264471b041a29774f43fb25b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea8ee0>: Failed to resolve 'app.legeth.cc' ([Errno -2] Name or service not known)""))"
http://www.qianlong520.top/api/v1/client/subscribe?token=8949b4b40ea3e7eec3764b38c0e89f13,0,失败,"请求失败: HTTPConnectionPool(host='www.qianlong520.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8949b4b40ea3e7eec3764b38c0e89f13 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d0a1a0>: Failed to resolve 'www.qianlong520.top' ([Errno -2] Name or service not known)""))"
https://4g.mkvn.net/api/v1/client/subscribe?token=c1021d8bc7bed367d0d7301086d0d056,0,失败,请求失败: 521 Server Error: <none> for url: https://4g.mkvn.net/api/v1/client/subscribe?token=c1021d8bc7bed367d0d7301086d0d056
https://api.sub-100.one/link/mUhF9ip9cxr06CPH,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.sub-100.one/link/mUhF9ip9cxr06CPH
https://api.sub-100.one/link/v1ZZPGra2NkpJTao?clash=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.sub-100.one/link/v1ZZPGra2NkpJTao?clash=3
http://panda.xn--lbrx91akmhm30c.com/api/v1/client/subscribe?token=3a3a14f2d494670a29b9bc61bff9d58d,0,失败,"请求失败: HTTPConnectionPool(host='panda.xn--lbrx91akmhm30c.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=3a3a14f2d494670a29b9bc61bff9d58d (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d09fc0>: Failed to resolve 'panda.xn--lbrx91akmhm30c.com' ([Errno -2] Name or service not known)""))"
http://suburl.xyz/sub/v2ray/03918642a18913311fe89c87808c0048ed3de173956276e48438d9ad4b2f47dfb9885e3f0f626fb7304af1e917c4cbb6ef7b8ffbb54485837ad1a05f273c42b9,0,成功,
https://42.194.232.60:10387/iplist/T3c2r8b8Jea2dVUn?sub=3,0,失败,内容过短
http://gbtgurl01.org/api/v1/client/subscribe?token=6ffdb23ecb80f2976136b2328bd8accd,0,失败,内容过短
https://45bcb080ade759e2.cdn.jiashule.com/api/v1/client/subscribe?token=3e6a33e4a4fe1e3c55d7aed672f6b494,0,失败,"请求失败: HTTPSConnectionPool(host='45bcb080ade759e2.cdn.jiashule.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3e6a33e4a4fe1e3c55d7aed672f6b494 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d094b0>: Failed to resolve '45bcb080ade759e2.cdn.jiashule.com' ([Errno -5] No address associated with hostname)""))"
https://api.ndsxfkjfvhzdsfio.quest/link/EVSrjRjZrNIbBqJB,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.ndsxfkjfvhzdsfio.quest/link/EVSrjRjZrNIbBqJB
https://7th-subscription-from-chickenfarmer.top/api/v1/client/subscribe?token=67f93a8a9df5ed8b89595f27d0fe3103,0,失败,内容过短
http://cdn1.ispisp.tk/api/v1/client/subscribe?token=3580102f2bc0f4a71866dd0e37e157c8,0,失败,"请求失败: HTTPConnectionPool(host='cdn1.ispisp.tk', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=3580102f2bc0f4a71866dd0e37e157c8 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea96f0>: Failed to resolve 'cdn1.ispisp.tk' ([Errno -2] Name or service not known)""))"
http://175.178.3.157:39393/api/v1/client/subscribe?token=5c30d98217f67f18f6ab5bf86f2b2bd4,0,失败,内容过短
http://wxshi.top:9090/clash/config,0,失败,"请求失败: HTTPConnectionPool(host='wxshi.top', port=9090): Max retries exceeded with url: /clash/config (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea85b0>: Failed to resolve 'wxshi.top' ([Errno -2] Name or service not known)""))"
http://62.234.18.232:8048/api/v1/client/subscribe?token=a05004f61e9fa5ebfad8ebf417b29efd,0,失败,请求超时
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=326448df01dd944eb5dd70523961a84c,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=326448df01dd944eb5dd70523961a84c (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://123.60.176.37:8000,0,失败,请求超时
http://s4.subcsyun.online/api/v1/client/subscribe?token=ad8995f33722feef0d16e3bcb7c2dd8b,0,成功,
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=113ea211f3a4c0810ba9cc30ff9436d6,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=113ea211f3a4c0810ba9cc30ff9436d6 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://bp.wbno1.xyz/api/v1/client/subscribe?token=09c5a704cba12b60c537f8512c99f52d,0,失败,请求失败: 522 Server Error:  for url: http://bp.wbno1.xyz/api/v1/client/subscribe?token=09c5a704cba12b60c537f8512c99f52d
https://api.ymvpnpro.cc:8700/7air2vr7ikiqzgvxz/api/v1/client/subscribe?token=924d44d49c2f390a4c28df82907c9b47,0,失败,内容过短
https://20240802.canadapost-vip.com/api/v1/client/subscribe?token=fa95a8fed800ed6f4a9e5f82493b0bf8,0,失败,"请求失败: HTTPSConnectionPool(host='20240802.canadapost-vip.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=fa95a8fed800ed6f4a9e5f82493b0bf8 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea8610>: Failed to resolve '20240802.canadapost-vip.com' ([Errno -2] Name or service not known)""))"
https://api.eutopiacloud.ml/api/v1/client/subscribe?token=a429b769e9d52f5fbffed5da7a9aec69,0,失败,"请求失败: HTTPSConnectionPool(host='api.eutopiacloud.ml', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a429b769e9d52f5fbffed5da7a9aec69 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d084c0>: Failed to resolve 'api.eutopiacloud.ml' ([Errno -2] Name or service not known)""))"
http://www.moguyun.xyz/api/v1/client/subscribe?token=03d4423ada1dadc24161da150c6b17f1,0,成功,
https://api1.fzdwf.top/api/v1/client/subscribe?token=67706c7a66b91ab14742f3e54771037f,61,成功,
http://panda.xn--lbrx91akmhm30c.com/api/v1/client/subscribe?token=bdde3a1e8dd64ebe24f3e432130b900f,0,失败,"请求失败: HTTPConnectionPool(host='panda.xn--lbrx91akmhm30c.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=bdde3a1e8dd64ebe24f3e432130b900f (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d09600>: Failed to resolve 'panda.xn--lbrx91akmhm30c.com' ([Errno -2] Name or service not known)""))"
http://cdn1.ispisp.tk/api/v1/client/subscribe?token=d1ea2c8870f28b58297389ba5535df62,0,失败,"请求失败: HTTPConnectionPool(host='cdn1.ispisp.tk', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=d1ea2c8870f28b58297389ba5535df62 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db0bb0>: Failed to resolve 'cdn1.ispisp.tk' ([Errno -2] Name or service not known)""))"
https://apiv2.lipulai.com/api_version2/dz1eclo3bwduxpd5?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='apiv2.lipulai.com', port=443): Max retries exceeded with url: /api_version2/dz1eclo3bwduxpd5?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d0a3b0>: Failed to resolve 'apiv2.lipulai.com' ([Errno -3] Temporary failure in name resolution)""))"
http://103.196.20.127/api/v1/client/subscribe?token=9f19fcc25b9345a928f76d7832dc7537,0,失败,"请求失败: HTTPConnectionPool(host='103.196.20.127', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=9f19fcc25b9345a928f76d7832dc7537 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8d08340>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://saobiwang.top/api/v1/client/subscribe?token=de56b9ecb62aa14484eed1a42894f53f,0,失败,"请求失败: HTTPConnectionPool(host='saobiwang.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=de56b9ecb62aa14484eed1a42894f53f (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea9090>: Failed to resolve 'saobiwang.top' ([Errno -2] Name or service not known)""))"
http://api.123417.xyz/api/v1/client/subscribe?token=84b21c9ad6dd351239d50994542e2137,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api.123417.xyz/api/v1/client/subscribe?token=84b21c9ad6dd351239d50994542e2137
https://a.kuaicloud.xyz/link/vxWfF6EBIeubvPyp?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/vxWfF6EBIeubvPyp?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8eaa4d0>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://30day.yxmm.xyz/7FA3F91B-2BBC-4945-AE49-9FD8753E771E,0,失败,"请求失败: HTTPSConnectionPool(host='30day.yxmm.xyz', port=443): Max retries exceeded with url: /7FA3F91B-2BBC-4945-AE49-9FD8753E771E (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db0c70>: Failed to resolve '30day.yxmm.xyz' ([Errno -5] No address associated with hostname)""))"
http://dingyue.myzone.site/link/79qL0kTwAOnENfek?clash=2,0,失败,内容过短
https://1.mjjclub.top/link/yZYoEfXhJ0BPWko8?sub=3,0,失败,内容过短
https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=7e891a8671f49a61ece23064e98f9362,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api1.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=7e891a8671f49a61ece23064e98f9362
https://a.sdwan.im/api/v1/client/subscribe?token=e78d3e6b5749e0d342b9dc12ac28f6f2,0,失败,请求失败: 403 Client Error: Forbidden for url: https://a.sdwan.im/api/v1/client/subscribe?token=e78d3e6b5749e0d342b9dc12ac28f6f2
https://a.kuaicloud.xyz/link/pcHp9ooqWVoM9e0M?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/pcHp9ooqWVoM9e0M?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea9e10>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
http://guolicheng.windowsupdate.lol/api/v1/client/subscribe?token=15da6769502d9e8ebcbb5582422a4192,0,成功,
https://5.52vpn.xyz/link/skbulhzug2hnkhrt?sub=3&amp;extend=1,0,失败,"请求失败: HTTPSConnectionPool(host='5.52vpn.xyz', port=443): Max retries exceeded with url: /link/skbulhzug2hnkhrt?sub=3&amp;extend=1 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1017)')))"
https://api.nutbit-node.lat/sub?token=1d1ee21c403c0560a8161147f3c8876c,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.nutbit-node.lat/sub?token=1d1ee21c403c0560a8161147f3c8876c
https://app.cloudlion.me/api/v1/client/subscribe?token=73016a0858c1a7afc2d81c8ccb382102,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=73016a0858c1a7afc2d81c8ccb382102
https://aiosjhdy.forbit-api.boats/sub?token=ee6034448472b57b0b757dc2ce2a26c0,0,失败,"请求失败: HTTPSConnectionPool(host='aiosjhdy.forbit-api.boats', port=443): Max retries exceeded with url: /sub?token=ee6034448472b57b0b757dc2ce2a26c0 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8d0a830>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://api.ymvpnpro.cc:8700/7air2vr7ikiqzgvxz/api/v1/client/subscribe?token=a5ba97552b9b1bdd07afa152e1457f1f,0,失败,内容过短
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=297c37f198e29be0377e8be9a88d9e37,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=297c37f198e29be0377e8be9a88d9e37
https://api1.441166.xyz/api/v1/client/subscribe?token=37044ea6ccafd4683fb03bb878586f5b,0,失败,"请求失败: HTTPSConnectionPool(host='api1.441166.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=37044ea6ccafd4683fb03bb878586f5b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d099c0>: Failed to resolve 'api1.441166.xyz' ([Errno -2] Name or service not known)""))"
https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=bf334803b5f594aab2206ad6b060994d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=bf334803b5f594aab2206ad6b060994d
https://abc.xn--8lt534m.ml/api/paste,0,失败,"请求失败: HTTPSConnectionPool(host='abc.xn--8lt534m.ml', port=443): Max retries exceeded with url: /api/paste (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db13f0>: Failed to resolve 'abc.xn--8lt534m.ml' ([Errno -2] Name or service not known)""))"
http://s3.subcsyun.online/api/v1/client/subscribe?token=eefad6017b1e873909e3030fa79a4e50,0,成功,
https://99ding.men/api/v1/client/subscribe?token=c85a6967e36949848c96f848cdb60a9b,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=c85a6967e36949848c96f848cdb60a9b
http://d.xyss.xyz/link/GwI70WZq3bVqdOpm?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='d.xyss.xyz', port=80): Max retries exceeded with url: /link/GwI70WZq3bVqdOpm?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d08850>: Failed to resolve 'd.xyss.xyz' ([Errno -2] Name or service not known)""))"
http://d.xyss.xyz/link/QzhaGySqW0H2nmpl?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='d.xyss.xyz', port=80): Max retries exceeded with url: /link/QzhaGySqW0H2nmpl?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea8c70>: Failed to resolve 'd.xyss.xyz' ([Errno -2] Name or service not known)""))"
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;flag=v2ray,0,成功,
http://106.75.78.111:10003/link/0QoRgeBhPGWcogjg?clash=1,0,失败,请求超时
https://apps.apple.com/ca/app/shadowrocket/id932747118,0,成功,
http://175.178.254.46/api/v1/client/subscribe?token=4155adbd333c333f221c2d88eda5ec2e,0,失败,"请求失败: HTTPConnectionPool(host='175.178.254.46', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4155adbd333c333f221c2d88eda5ec2e (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8db1210>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://1.1598888.xyz/api/v1/client/subscribe?token=1dec5121c95e504f667efe2705e0b1ff,0,失败,请求超时
http://s1.subcsyun.online/api/v1/client/subscribe?token=30db03460bbf9d093fad84d653f58af8,0,成功,
http://8.134.181.161:12580/md5/y0GPbMNmSD9pYD0k?sub=3,0,失败,内容过短
https://api.acaisbest.shop/api/v1/client/subscribe?token=ea7046282fc195883735eb31b9cbc8f4,0,失败,"请求失败: HTTPSConnectionPool(host='api.acaisbest.shop', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=ea7046282fc195883735eb31b9cbc8f4 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d08520>: Failed to resolve 'api.acaisbest.shop' ([Errno -3] Temporary failure in name resolution)""))"
https://ap.niubi.site/api/v1/client/subscribe?token=ed6696b292aeecf073a223666f2cf6de,0,失败,"请求失败: HTTPSConnectionPool(host='ap.niubi.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=ed6696b292aeecf073a223666f2cf6de (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db1480>: Failed to resolve 'ap.niubi.site' ([Errno -5] No address associated with hostname)""))"
https://14ce7f2b-1b99-417c-ab7b-6de0d94baec8.apcdn.org/api/v1/client/subscribe?token=e073fbc63fd416f45fa4d0175e2ba5d4,0,失败,内容过短
https://a.kuaicloud.xyz/link/v1vR56eYlRCQ4lNl?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/v1vR56eYlRCQ4lNl?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea8c70>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
http://server.imhup.com:8880/api/v1/client/subscribe?token=ae1a2a975075380ccc026c43d851e500,0,失败,"请求失败: HTTPConnectionPool(host='server.imhup.com', port=8880): Max retries exceeded with url: /api/v1/client/subscribe?token=ae1a2a975075380ccc026c43d851e500 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db06d0>: Failed to resolve 'server.imhup.com' ([Errno -2] Name or service not known)""))"
https://20240802.canadapost-vip.com/api/v1/client/subscribe?token=fa95a8fed800ed6f4a9e5f82493b0bf8&amp;flag=meta,0,失败,"请求失败: HTTPSConnectionPool(host='20240802.canadapost-vip.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=fa95a8fed800ed6f4a9e5f82493b0bf8&amp;flag=meta (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db1990>: Failed to resolve '20240802.canadapost-vip.com' ([Errno -2] Name or service not known)""))"
https://amatrixap.com/link/cPH2fRQQhtF8p7Kl?clash=1,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/cPH2fRQQhtF8p7Kl?clash=1
http://realnode.me/api/v1/client/subscribe?token=4b37d42218c6fd1d8b9738b4e9aa182a,0,失败,"请求失败: HTTPConnectionPool(host='realnode.me', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4b37d42218c6fd1d8b9738b4e9aa182a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea9b40>: Failed to resolve 'realnode.me' ([Errno -2] Name or service not known)""))"
https://3093492f6b2332f8server.lycoris.one/api/v1/client/subscribe?token=fc5c4b3ee340edb61c1be5d33589d25d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://3093492f6b2332f8server.lycoris.one/api/v1/client/subscribe?token=fc5c4b3ee340edb61c1be5d33589d25d
https://api.jsm.one/link/8uiI7igbUZbnVyL0?clash=1,0,失败,内容过短
http://jjz.31465.cfd/api/v1/client/subscribe?token=4c55b1a88f0dd170cf89573cf9ba65be,0,失败,内容过短
https://1321078938-11mmjf3qkb-hk.scf.tencentcs.com/api/v1/client/subscribe?token=cb1270a6aa0980c4de79b49aad8098f7,2,成功,
http://sub.hxlgaozhong.xyz/api/v1/client/subscribe?token=fdf29c988ac773a9f9c67a922176043b,0,失败,"请求失败: HTTPConnectionPool(host='sub.hxlgaozhong.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=fdf29c988ac773a9f9c67a922176043b (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d08850>: Failed to resolve 'sub.hxlgaozhong.xyz' ([Errno -2] Name or service not known)""))"
https://api.nscloud.app/api/v1/client/subscribe?token=d949373780e0617bfdbd3ffdfd4e461e,0,失败,"请求失败: HTTPSConnectionPool(host='api.nscloud.app', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d949373780e0617bfdbd3ffdfd4e461e (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db1fc0>: Failed to resolve 'api.nscloud.app' ([Errno -2] Name or service not known)""))"
https://api.meomiao.us/api/v1/client/subscribe?token=86253fbae66ba3cb68a663253578ec23,0,失败,请求超时
https://069059b7ef-1ytapi01.1ytsub.com/api/v1/client/subscribe?token=4dba956d33f8cb4ad60b6a3cbc76bdd9,0,失败,内容过短
https://api.tshl.cc/link/ry6M2vbmr2bGYspl?mu=2,0,失败,内容过短
https://api.skyrocketapi.xyz/api/v1/client/subscribe?token=097b78b0d5ecd3030bd9b4bedca3718b,0,失败,"请求失败: HTTPSConnectionPool(host='api.skyrocketapi.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=097b78b0d5ecd3030bd9b4bedca3718b (Caused by SSLError(SSLError(1, '[SSL: TLSV1_UNRECOGNIZED_NAME] tlsv1 unrecognized name (_ssl.c:1017)')))"
https://api.xjichang.buzz/api/v1/client/subscribe?token=3b3e2c230fb4aaf03161458f521eab14,0,失败,"请求失败: HTTPSConnectionPool(host='api.xjichang.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3b3e2c230fb4aaf03161458f521eab14 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfec280>: Failed to resolve 'api.xjichang.buzz' ([Errno -2] Name or service not known)""))"
https://api.xinyo.vip/api/v1/client/subscribe?token=5a563d7330dd13ce16ec909ea4257548,2,成功,
http://101.200.14.80:3325/api/v1/client/subscribe?token=4bbd5149d786e6ead646d4b5bbaee6a8,0,失败,请求失败: 404 Client Error: Not Found for url: http://101.200.14.80:3325/api/v1/client/subscribe?token=4bbd5149d786e6ead646d4b5bbaee6a8
https://api.ndsxfkjfvhzdsfio.quest/link/EVSrjRjZrNIbBqJB?clash=1,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.ndsxfkjfvhzdsfio.quest/link/EVSrjRjZrNIbBqJB?clash=1
https://088EA81A-3547-85E0-4AF6-DFCB3C6674AA.372372.xyz/api/v1/client/subscribe?token=d3065c795c0ea07c325756a2515708d9,0,失败,内容过短
http://104.168.244.47:12580/clash/proxies,0,失败,"请求失败: HTTPConnectionPool(host='104.168.244.47', port=12580): Max retries exceeded with url: /clash/proxies (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8d09c90>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://abc111222.top/api/v1/client/subscribe?token=2dc6c546bf938dbabb505eb14f7668e8,0,成功,
https://a.kuaicloud.xyz/link/g5dKnfsXrxDxj6O4?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/g5dKnfsXrxDxj6O4?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd45e0>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://1ytcom01.1yunti.net/api/v1/client/subscribe?token=a4f4afd3c81a694441731c64dbe17d47,0,失败,请求失败: 403 Client Error: Forbidden for url: https://1ytcom01.1yunti.net/api/v1/client/subscribe?token=a4f4afd3c81a694441731c64dbe17d47
http://subs.202218.xyz/link/Z62ruypNEOK5RRrm?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/Z62ruypNEOK5RRrm?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db24d0>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
http://www.a100.sbs/api/v1/client/subscribe?token=68ba72714ad5f8fe616ef74598e2b5a4,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ww38.a100.sbs/api/v1/client/subscribe?token=68ba72714ad5f8fe616ef74598e2b5a4
http://aelr.cc/link/c5b8JHoR8UObj3Hu?clash=1,0,失败,请求失败: 404 Client Error: Not Found for url: http://www.aelr.cc/link/c5b8JHoR8UObj3Hu?clash=1
http://v3.pkqshidazhubi.live/api/v1/client/subscribe?token=37624ad18dd626a21cfb1a43c39b460c,0,失败,"请求失败: HTTPConnectionPool(host='v3.pkqshidazhubi.live', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=37624ad18dd626a21cfb1a43c39b460c (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db3be0>: Failed to resolve 'v3.pkqshidazhubi.live' ([Errno -2] Name or service not known)""))"
https://app.lwjyj.com/api/v1/client/subscribe?token=a487984eee4196625ba8e75b362b7467,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.lwjyj.com/api/v1/client/subscribe?token=a487984eee4196625ba8e75b362b7467
https://a.kuaicloud.xyz/link/97aenyYFPiu3ilHG?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='a.kuaicloud.xyz', port=443): Max retries exceeded with url: /link/97aenyYFPiu3ilHG?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd40a0>: Failed to resolve 'a.kuaicloud.xyz' ([Errno -2] Name or service not known)""))"
https://03.laomao1.xyz/api/v1/client/subscribe?token=4da7652c1212c83fb1f540c23e0ca0fd,0,失败,"请求失败: HTTPSConnectionPool(host='03.laomao1.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=4da7652c1212c83fb1f540c23e0ca0fd (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd5000>: Failed to resolve '03.laomao1.xyz' ([Errno -2] Name or service not known)""))"
http://106.15.63.84:39391/api/zhiji?token=56e3973ad04359ab58ba7984709576d9,0,失败,请求超时
http://ggiuwegivhe123.a123.bond/api/v1/client/subscribe?token=4c5f066d2f41864c780a7ff5af9f4a70,0,失败,请求失败: 404 Client Error: Not Found for url: http://ggiuwegivhe123.a123.bond/api/v1/client/subscribe?token=4c5f066d2f41864c780a7ff5af9f4a70
http://sub.hideu.cc/api/sub/lUoukmdnE35,0,失败,"请求失败: HTTPConnectionPool(host='sub.hideu.cc', port=80): Max retries exceeded with url: /api/sub/lUoukmdnE35 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db1060>: Failed to resolve 'sub.hideu.cc' ([Errno -2] Name or service not known)""))"
https://app.gomeow.cloud/api/v1/client/subscribe?token=045d419eebea145c60f29f6f8ac51d8d,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.gomeow.cloud/api/v1/client/subscribe?token=045d419eebea145c60f29f6f8ac51d8d
http://loongqing.me/test-your-clash.yaml,0,失败,"请求失败: HTTPConnectionPool(host='loongqing.me', port=80): Max retries exceeded with url: /test-your-clash.yaml (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db3b50>: Failed to resolve 'loongqing.me' ([Errno -2] Name or service not known)""))"
https://api.acaisbest.shop/api/v1/client/subscribe?token=8c688dd0c67cfa63f989f0689ada2ddf,0,失败,"请求失败: HTTPSConnectionPool(host='api.acaisbest.shop', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=8c688dd0c67cfa63f989f0689ada2ddf (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfecdf0>: Failed to resolve 'api.acaisbest.shop' ([Errno -3] Temporary failure in name resolution)""))"
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=b34b2e4e8eeec829e368fd631b20fbd1,0,失败,内容过短
https://66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com/api/v1/client/subscribe?token=f938ea88aaed45e7fd27d36e93dff2d0&amp;flag=clash,0,失败,"请求失败: HTTPSConnectionPool(host='66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f938ea88aaed45e7fd27d36e93dff2d0&amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d09a50>: Failed to resolve '66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com' ([Errno -2] Name or service not known)""))"
http://lafusees.com/api/v1/client/subscribe?token=39edf5449d8183acb2ba620afe831578,0,失败,请求失败: 404 Client Error: Not Found for url: http://lafusees.com/api/v1/client/subscribe?token=39edf5449d8183acb2ba620afe831578
http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=b83d35fbeb50393b3595b0ca49e4f60b,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api-0609.m55u97uleod7lm5.download/api/v1/client/subscribe?token=b83d35fbeb50393b3595b0ca49e4f60b
http://www.bfyun.top/api/v1/client/subscribe?token=c157db6296854aaa09ad2747d7d0c77c,0,失败,"请求失败: HTTPConnectionPool(host='www.bfyun.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c157db6296854aaa09ad2747d7d0c77c (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbfefa00>: Failed to resolve 'www.bfyun.top' ([Errno -2] Name or service not known)""))"
https://apiv2.pptiok2020.com/apiv2/vjgb7lsudev7yhch?clash=2&amp;extend=1,0,失败,内容过短
https://17.laomao1.xyz/api/v1/client/subscribe?token=16e693207721710f1ee41184a906ba9c,0,失败,"请求失败: HTTPSConnectionPool(host='17.laomao1.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=16e693207721710f1ee41184a906ba9c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfed450>: Failed to resolve '17.laomao1.xyz' ([Errno -2] Name or service not known)""))"
https://app.cloudlion.me/api/v1/client/subscribe?token=6f9e141c70cb41781c9cfe41057d24c3&amp;types=all,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=6f9e141c70cb41781c9cfe41057d24c3&amp;types=all
https://api.bigme.online:8211/api/v1/client/subscribe?token=6674c05d3297078394f93ece18e5be9c,0,成功,
https://api.meomiao.me/api/v1/client/subscribe?token=e635cfa4d9718eb855c452ae5b5e4eeb,0,失败,"请求失败: HTTPSConnectionPool(host='api.meomiao.me', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e635cfa4d9718eb855c452ae5b5e4eeb (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfeecb0>: Failed to resolve 'api.meomiao.me' ([Errno -2] Name or service not known)""))"
http://dy.xyyjc.top/api/v1/client/subscribe?token=ba818ce7fa4c404ae1ee19f4ed9ad98d&amp;flag=meta,0,成功,
https://3h.lv/api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c&amp;amp;flag=clash,0,失败,"请求失败: HTTPSConnectionPool(host='3h.lv', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=32df6680956d6fc43bceea2a0b49202c&amp;amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfeebf0>: Failed to resolve '3h.lv' ([Errno -2] Name or service not known)""))"
https://a1.8jiasu.com/api/v1/client/subscribe?token=fe6b4b8e17135129f6836a85c1d63083,0,失败,内容过短
http://173.249.198.78/api/v1/client/subscribe?token=cebccdacd45b9452ebff09a8a6a37950,0,失败,请求超时
http://dd.ewmld2.one/api/v1/client/subscribe?token=7f077ab7a1caae73cc32c4897ddd468b,0,失败,"请求失败: HTTPConnectionPool(host='dd.ewmld2.one', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=7f077ab7a1caae73cc32c4897ddd468b (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd4d90>: Failed to resolve 'dd.ewmld2.one' ([Errno -2] Name or service not known)""))"
https://81a6e0cd-5a8a-3500-997d-d7b3b73465d3.huaweippy.com/link/jtYu0a5LV59HhZfo?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='81a6e0cd-5a8a-3500-997d-d7b3b73465d3.huaweippy.com', port=443): Max retries exceeded with url: /link/jtYu0a5LV59HhZfo?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfeebf0>: Failed to resolve '81a6e0cd-5a8a-3500-997d-d7b3b73465d3.huaweippy.com' ([Errno -2] Name or service not known)""))"
http://by.xbygood.xyz/link/evi3Mp6M4GOqSoHN?clash=1,0,失败,请求失败: 502 Server Error: Bad Gateway for url: http://ww12.xbygood.xyz/link/evi3Mp6M4GOqSoHN?clash=1&usid=26&utid=12247550134
https://001.6891256.xyz/api/v1/client/subscribe?token=d6011b26a19e285c455ae825f9307ed3,0,失败,"请求失败: HTTPSConnectionPool(host='001.6891256.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d6011b26a19e285c455ae825f9307ed3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db3b20>: Failed to resolve '001.6891256.xyz' ([Errno -2] Name or service not known)""))"
https://18.laomao1.xyz/api/v1/client/subscribe?token=06e36b1c4b7900ff263d574afa8f3f61,0,失败,"请求失败: HTTPSConnectionPool(host='18.laomao1.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=06e36b1c4b7900ff263d574afa8f3f61 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfee740>: Failed to resolve '18.laomao1.xyz' ([Errno -2] Name or service not known)""))"
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=a9236b831f8019a4914004d9dabca481,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a9236b831f8019a4914004d9dabca481 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://api.prprcloud.life/clash/7492/gy2jFqUWYJ/,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://api.prprcloud.life/clash/7492/gy2jFqUWYJ/
https://app.legeth.cc/api/v1/client/subscribe?token=d2d9b394aac6ddf358a4ace03e532fb8,0,失败,"请求失败: HTTPSConnectionPool(host='app.legeth.cc', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d2d9b394aac6ddf358a4ace03e532fb8 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4340>: Failed to resolve 'app.legeth.cc' ([Errno -2] Name or service not known)""))"
http://g3.03184.com:8091/F_20241011160900vrqpbf/111.yaml,86,成功,
https://apiv2.lemongg.top/api/v1/client/subscribe?token=f2478b2017fff29be5e0f8137b6b478c,0,失败,"请求失败: HTTPSConnectionPool(host='apiv2.lemongg.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f2478b2017fff29be5e0f8137b6b478c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c204c0>: Failed to resolve 'apiv2.lemongg.top' ([Errno -2] Name or service not known)""))"
http://g3i.buzz/v3/subscr?id=0998cfcf655b4e618b3a267fd3176a7a,0,失败,内容过短
https://api.misakanet.buzz/api/v1/client/subscribe?token=f82e5fe1d549a2b9d97c37857b6872fa,0,失败,"请求失败: HTTPSConnectionPool(host='api.misakanet.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f82e5fe1d549a2b9d97c37857b6872fa (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c21210>: Failed to resolve 'api.misakanet.buzz' ([Errno -2] Name or service not known)""))"
http://103.196.20.127/api/v1/client/subscribe?token=f1279af04744dd54210317fd8ca4eb46,0,失败,"请求失败: HTTPConnectionPool(host='103.196.20.127', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=f1279af04744dd54210317fd8ca4eb46 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8c23070>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://api7.6yuan.top/api/v1/client/subscribe?token=d1bdb8257abebbcfec16e2f874123138,0,失败,"请求失败: HTTPSConnectionPool(host='api7.6yuan.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d1bdb8257abebbcfec16e2f874123138 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c218a0>: Failed to resolve 'api7.6yuan.top' ([Errno -2] Name or service not known)""))"
https://676b5c.whisperingbreeze.cc/api/v1/client/subscribe?token=e253a809d0c1ad3153feb4eb6907e745,0,失败,请求失败: 403 Client Error: Forbidden for url: https://676b5c.whisperingbreeze.cc/api/v1/client/subscribe?token=e253a809d0c1ad3153feb4eb6907e745
http://yuwan027.xyz/api/v1/client/subscribe?token=57ee7721725dd1d95a2d03365e3ece64,0,失败,"请求失败: HTTPConnectionPool(host='yuwan027.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=57ee7721725dd1d95a2d03365e3ece64 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8c22230>: Failed to resolve 'yuwan027.xyz' ([Errno -2] Name or service not known)""))"
http://lianjiasub.work/api/v1/client/subscribe?token=7ee2534e93ce37f1f6c7b3d18c8a02b0,0,失败,请求失败: 403 Client Error: Forbidden for url: http://lianjiasub.work/api/v1/client/subscribe?token=7ee2534e93ce37f1f6c7b3d18c8a02b0
https://ap.niaodi.top/niao?token=de3d75d981f9e39cf2d592e3498248ce,0,失败,内容过短
https://app.ppssqq.com/link/O5DenNePHAGFubRs?sub=3,0,失败,"请求失败: HTTPSConnectionPool(host='app.ppssqq.com', port=443): Max retries exceeded with url: /link/O5DenNePHAGFubRs?sub=3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c23490>: Failed to resolve 'app.ppssqq.com' ([Errno -2] Name or service not known)""))"
https://440300.xyz/api/v1/client/subscribe?token=761f8d7cbb197d5ca1d0ff7692486318,0,失败,"请求失败: HTTPSConnectionPool(host='440300.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=761f8d7cbb197d5ca1d0ff7692486318 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c22620>: Failed to resolve '440300.xyz' ([Errno -5] No address associated with hostname)""))"
https://apisub.mcwy.xyz/api/v1/client/subscribe?token=89424b5caa87f0bfc5d05da83c330764,0,失败,请求失败: 403 Client Error: Forbidden for url: https://apisub.mcwy.xyz/api/v1/client/subscribe?token=89424b5caa87f0bfc5d05da83c330764
https://1g.gay/?v2b=yq1.jixunyou02.com,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=yq1.jixunyou02.com (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c217e0>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=cbb31425affb0704414d28c596a57d0e,0,失败,请求失败: 403 Client Error: Forbidden for url: https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=cbb31425affb0704414d28c596a57d0e
http://dy.changyouVPN.top/api/v1/client/subscribe?token=e366bfd147292b2d6df2f36151c80547,0,失败,内容过短
http://1.1598888.xyz/api/v1/client/subscribe?token=e2c8421cd8543cd904f255fbef4490cd,0,失败,请求超时
http://dd.cxld.sbs/api/v1/client/subscribe?token=bbca21899f2e97ef66dca25d3b9466ca,0,失败,"请求失败: HTTPConnectionPool(host='dd.cxld.sbs', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=bbca21899f2e97ef66dca25d3b9466ca (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8c20130>: Failed to resolve 'dd.cxld.sbs' ([Errno -2] Name or service not known)""))"
https://22.lownet.xyz/api/v1/client/subscribe?token=83b9ac408ca43c43f99a54209020ec77,0,失败,请求失败: 403 Client Error: Forbidden for url: https://22.lownet.xyz/api/v1/client/subscribe?token=83b9ac408ca43c43f99a54209020ec77
https://api-zz.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=3df39719aadc30954859a312a7715447,0,失败,请求失败: 522 Server Error: <none> for url: https://api-zz.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=3df39719aadc30954859a312a7715447
https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=584e6a28ada9a8f5fb01ae955ea83de2,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=584e6a28ada9a8f5fb01ae955ea83de2
http://1.1596666.xyz/api/v1/client/subscribe?token=6de50127188bebfe62e3b5565097cc88,0,失败,请求超时
http://188.213.196.100:8585/sip002/sub,0,失败,"请求失败: HTTPConnectionPool(host='188.213.196.100', port=8585): Max retries exceeded with url: /sip002/sub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8c21090>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://wy.hkaa0.top/sub/,0,失败,请求失败: 403 Client Error: Forbidden for url: https://wy.hkaa0.top/sub/
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=6d356f188634de6f14b70c20488b5079,0,失败,内容过短
http://cloudupup.com/link/dofxp41jG8y4oC9N?clash=1,0,成功,
https://abc.xn--8lt534m.ml/api/text,0,失败,"请求失败: HTTPSConnectionPool(host='abc.xn--8lt534m.ml', port=443): Max retries exceeded with url: /api/text (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c237c0>: Failed to resolve 'abc.xn--8lt534m.ml' ([Errno -2] Name or service not known)""))"
http://gbtgurl01.org/api/v1/client/subscribe?token=f6ce5f890330d86511e70ff340ea2c73,0,失败,请求失败: 403 Client Error: Forbidden for url: http://gbtgurl01.org/api/v1/client/subscribe?token=f6ce5f890330d86511e70ff340ea2c73
http://xbvpn.vip/api/v1/client/subscribe?token=228c3d63fc70a86624f2220c31e756cd,0,失败,请求失败: 404 Client Error: Not Found for url: http://aecc.pro/api/v1/client/subscribe?token=228c3d63fc70a86624f2220c31e756cd
http://fjcm.121628.xyz/sub/1121.txt,0,失败,请求超时
https://774.gs/FPWu,0,失败,请求失败: 403 Client Error: Forbidden for url: https://yuyan.online/api/v1/client/subscribe?token=280e89d3e5a3ea4c0c87ab97a42c6738
http://dy.luoxin.fun/link/ENIp1Kbx9oeQMETd?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='dy.luoxin.fun', port=80): Max retries exceeded with url: /link/ENIp1Kbx9oeQMETd?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8c225f0>: Failed to resolve 'dy.luoxin.fun' ([Errno -2] Name or service not known)""))"
http://569cdn.1010520.click/api/v1/client/subscribe?token=3954389ab29911c7d275d9a9f8aaaf8b,0,失败,请求失败: 403 Client Error: Forbidden for url: http://569cdn.1010520.click/api/v1/client/subscribe?token=3954389ab29911c7d275d9a9f8aaaf8b
https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=e6d1fa51b80903d94df51977ebf4a33e,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=e6d1fa51b80903d94df51977ebf4a33e
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;amp;amp;flag=v2ray,0,成功,
https://a.mtdwoodwork.com/api/v1/client/subscribe?token=1d371dbc16749d074eb7b927b76b3d6b,0,失败,请求失败: 526 Server Error: <none> for url: https://a.mtdwoodwork.com/api/v1/client/subscribe?token=1d371dbc16749d074eb7b927b76b3d6b
http://msvpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=9ff4246cba59721acc3c74bd893d1886,0,失败,请求失败: 404 Client Error: Not Found for url: http://msvpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=9ff4246cba59721acc3c74bd893d1886
https://api.1122jump3344.net/api/v1/client/subscribe?token=4b3ccb7d21e14a2999eef8114f66c4ae,0,失败,"请求失败: HTTPSConnectionPool(host='api.1122jump3344.net', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=4b3ccb7d21e14a2999eef8114f66c4ae (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c20100>: Failed to resolve 'api.1122jump3344.net' ([Errno -2] Name or service not known)""))"
https://66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com/api/v1/client/subscribe?token=f938ea88aaed45e7fd27d36e93dff2d0,0,失败,"请求失败: HTTPSConnectionPool(host='66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f938ea88aaed45e7fd27d36e93dff2d0 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed89a0>: Failed to resolve '66195e16-0a53-4563-8515-f6f97d22f4ef.fengchenginx.com' ([Errno -2] Name or service not known)""))"
https://api.xqc.best/api/v1/client/subscribe?token=116ea138d237fe0cfa8e51c114062aae,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=116ea138d237fe0cfa8e51c114062aae (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://apidy.pqjc.site/api/v1/client/subscribe?token=4b7304a96f96120b5f13d0f2edc56437,0,失败,请求失败: 403 Client Error: Forbidden for url: https://apidy.pqjc.site/api/v1/client/subscribe?token=4b7304a96f96120b5f13d0f2edc56437
http://s.33y.run/v3/subscr?id=fddfab8122bb4d338e95933c8c81b2ad,0,失败,请求失败: 403 Client Error: Forbidden for url: https://s.33y.run/v3/subscr?id=fddfab8122bb4d338e95933c8c81b2ad
https://api.abyssyun.top/api/v1/client/subscribe?token=b2461a92a0d67ab065a2140d5b477d6f,0,成功,
http://dy.changyouVPN.top/api/v1/client/subscribe?token=925a34c938f91d3cd6cf9189fb16673d,0,失败,内容过短
http://api.sgjc.xyz/api/v1/client/subscribe?token=c015034bf0912b4eff60bd867465c45e,0,成功,
http://106.75.78.111:10003/link/YxrcNgl8tZzj44Qs?clash=1,0,失败,请求超时
https://422.jcool.cool/api/v1/client/subscribe?token=7651bcba974baefaf929e408444d27d4&amp;amp;ttoken=767d2f8ed5d21a44b,0,失败,"请求失败: HTTPSConnectionPool(host='422.jcool.cool', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=7651bcba974baefaf929e408444d27d4&amp;amp;ttoken=767d2f8ed5d21a44b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c223b0>: Failed to resolve '422.jcool.cool' ([Errno -2] Name or service not known)""))"
https://api.xn--y20az5i.xyz/api/v1/client/subscribe?token=99629bba2c597d9334d8b20ca701f9b1,0,失败,"请求失败: HTTPSConnectionPool(host='api.xn--y20az5i.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=99629bba2c597d9334d8b20ca701f9b1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8880>: Failed to resolve 'api.xn--y20az5i.xyz' ([Errno -2] Name or service not known)""))"
https://api.freelandernet.org/api/v1/client/subscribe?token=0bdcb92757e0f4f2de9dc97fe2669578,0,失败,"请求失败: HTTPSConnectionPool(host='api.freelandernet.org', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=0bdcb92757e0f4f2de9dc97fe2669578 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c23850>: Failed to resolve 'api.freelandernet.org' ([Errno -2] Name or service not known)""))"
http://msvpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=ef7fe3ef9481e7d8b5894f750bd3d69b,0,失败,请求失败: 404 Client Error: Not Found for url: http://msvpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=ef7fe3ef9481e7d8b5894f750bd3d69b
https://20.laomao1.xyz/api/v1/client/subscribe?token=11cda22827f51ac90e55d103e9636e9b,0,失败,"请求失败: HTTPSConnectionPool(host='20.laomao1.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=11cda22827f51ac90e55d103e9636e9b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c22da0>: Failed to resolve '20.laomao1.xyz' ([Errno -2] Name or service not known)""))"
https://app.cloudlion.me/api/v1/client/subscribe?token=e759c440f53a07f75f4d6455239cb017,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=e759c440f53a07f75f4d6455239cb017
https://00.222333123.xyz/api/v1/client/subscribe?token=d685a67e6e82f70997e2fae417cd483d,0,失败,"请求失败: HTTPSConnectionPool(host='00.222333123.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d685a67e6e82f70997e2fae417cd483d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed8490>: Failed to resolve '00.222333123.xyz' ([Errno -2] Name or service not known)""))"
http://w.aksex.top/api/v1/client/subscribe?token=c964cc231fd9535d5b6a86351fbb4d36,0,失败,"请求失败: HTTPConnectionPool(host='w.aksex.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c964cc231fd9535d5b6a86351fbb4d36 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed8eb0>: Failed to resolve 'w.aksex.top' ([Errno -2] Name or service not known)""))"
http://vps.huanshi88.sbs/api/v1/client/subscribe?token=babaca678101e548138df118bdc2263d,0,成功,
http://dy.changyouVPN.top/api/v1/client/subscribe?token=ae2d46b360f66cfb6c3e7e0d651c2a86,0,失败,内容过短
https://amatrixap.com/link/YE5NaErHPK9YNEUl?sub=3,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/YE5NaErHPK9YNEUl?sub=3
https://1g.gay/?v2b=huamaoyun.live,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=huamaoyun.live (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb16bfd0>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
https://10th.sub-airport.com/api/v1/client/subscribe?token=634cc630b2d8e2f3bba5472c67d2e5a2,0,失败,"请求失败: HTTPSConnectionPool(host='10th.sub-airport.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=634cc630b2d8e2f3bba5472c67d2e5a2 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8c23af0>: Failed to resolve '10th.sub-airport.com' ([Errno -2] Name or service not known)""))"
http://cdn1.ispisp.tk/api/v1/client/subscribe?token=cbfed82cfe0bc31a021ec03c1ce085b5,0,失败,"请求失败: HTTPConnectionPool(host='cdn1.ispisp.tk', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=cbfed82cfe0bc31a021ec03c1ce085b5 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1e2c0>: Failed to resolve 'cdn1.ispisp.tk' ([Errno -2] Name or service not known)""))"
https://1.bethebest.eu.org/api/v1/client/subscribe?token=3715a07dc448ad9f275aa73e54b762b7,0,失败,请求失败: 403 Client Error: Forbidden for url: https://1.bethebest.eu.org/api/v1/client/subscribe?token=3715a07dc448ad9f275aa73e54b762b7
https://a.jiedianxielou.workers.dev/api/v1/client/subscribe?token=UjBGOXVrdFBKYzl0dE5SK3M5Nk84Tkp2T2M0YW1jVk02d0FxbmQ2Q3l5UGF3QkJhUW1CUHNTSzNhOXJmMDFHcXJ4NE51VGpsaVlwMGgzbUgvT1pLQkRMTUhRS2xwYnFEVUNtMzN5OTBabEhwRVE9PQ,7,成功,
http://dy.luoxin.fun/link/I5pDOfakaizAboW8?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='dy.luoxin.fun', port=80): Max retries exceeded with url: /link/I5pDOfakaizAboW8?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed8cd0>: Failed to resolve 'dy.luoxin.fun' ([Errno -2] Name or service not known)""))"
https://api.xfltd.xyz/api/v1/client/subscribe?token=58e0e583f19a6277ecb51582b3771e47,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xfltd.xyz/api/v1/client/subscribe?token=58e0e583f19a6277ecb51582b3771e47
http://lumine.sumeru.design/?name=pmn.clash,0,失败,"请求失败: HTTPConnectionPool(host='lumine.sumeru.design', port=80): Max retries exceeded with url: /?name=pmn.clash (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ed9180>: Failed to resolve 'lumine.sumeru.design' ([Errno -2] Name or service not known)""))"
http://sub.sub.sub.subsub123456789.com/answer/land?token=78ea2aeb10cd3cc125e5aad51e1731ab,0,失败,内容过短
http://sp.nfsq.me/api/v1/client/subscribe?token=ec04640ee200916f5bbbc607ebfe8f3a,0,成功,
https://a.jiedianxielou.workers.dev/api/v1/client/subscribe?token=UjBGOXVrdFBKYzl0dE04ODdacUFzOTlrTU04RGtOWk0vRUZzMGNUYWdTN0NoZ1pCVkR4ZnRpbW1iWmZDM2wvd3RVeFY3ekM4aHRwNmhIS0UrYkFhQlRHY1NBZWdxYnlEVkNlK2lpRW5aZ1M3RWN0Y1VvVT0,7,成功,
https://3dxre.no-mad-world.club/link/4BJUHDdrBdPAQN1U?clash=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://3dxre.no-mad-world.club/link/4BJUHDdrBdPAQN1U?clash=3
http://jshou.top/api/v1/client/subscribe?token=e408407f35990974c5ae61a92c866923,0,失败,"请求失败: HTTPConnectionPool(host='jshou.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=e408407f35990974c5ae61a92c866923 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b83a51b0>: Failed to resolve 'jshou.top' ([Errno -5] No address associated with hostname)""))"
https://api.star-dr.com/link/pd7cjjz1qztprotc?sub=4,0,失败,"请求失败: HTTPSConnectionPool(host='api.star-dr.com', port=443): Max retries exceeded with url: /link/pd7cjjz1qztprotc?sub=4 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ea98a0>: Failed to resolve 'api.star-dr.com' ([Errno -2] Name or service not known)""))"
http://v2-1.806cms.top/api/v1/client/subscribe?token=652be51577866d965bebfbb471c2d2fc,0,失败,"请求失败: HTTPConnectionPool(host='v2-1.806cms.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=652be51577866d965bebfbb471c2d2fc (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8ea9870>: Failed to resolve 'v2-1.806cms.top' ([Errno -2] Name or service not known)""))"
http://108.60.201.16/v10/HongKong/GCP/V1,0,失败,请求超时
https://app.jisovpn.site/api/v1/client/subscribe?token=5fc3e6eb0c07f3e3c11a5615618cac68,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5fc3e6eb0c07f3e3c11a5615618cac68 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8db2cb0>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
http://dy.luoxin.fun/link/QxwsGBUhaGmRCFTf?sub=3,0,失败,"请求失败: HTTPConnectionPool(host='dy.luoxin.fun', port=80): Max retries exceeded with url: /link/QxwsGBUhaGmRCFTf?sub=3 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db24a0>: Failed to resolve 'dy.luoxin.fun' ([Errno -2] Name or service not known)""))"
http://3093492f6b2332f8server.lycoris.one/api/v1/client/subscribe?token=06f54517cccb379edd1a1be807cc9c2a,0,失败,请求失败: 404 Client Error: Not Found for url: http://3093492f6b2332f8server.lycoris.one/api/v1/client/subscribe?token=06f54517cccb379edd1a1be807cc9c2a
http://1.1596666.xyz/api/v1/client/subscribe?token=1dec5121c95e504f667efe2705e0b1ff,0,失败,请求超时
http://g3.03184.com:8091/F_20241011160900vrqpbf/clash.yaml,106,成功,
http://ciallo.elegy.icu:7001/api/v1/client/subscribe?token=e4d5aaf1559555cae1bad8e5b6495d8f,0,失败,"请求失败: HTTPConnectionPool(host='ciallo.elegy.icu', port=7001): Max retries exceeded with url: /api/v1/client/subscribe?token=e4d5aaf1559555cae1bad8e5b6495d8f (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4cb1cdb40>: Failed to resolve 'ciallo.elegy.icu' ([Errno -2] Name or service not known)""))"
http://subs.202218.xyz/link/IEgVIFtLrHprvnpD?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/IEgVIFtLrHprvnpD?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd4280>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
http://lsdy.clearto.cc/lsdy,0,失败,"请求失败: HTTPConnectionPool(host='lsdy.clearto.cc', port=80): Max retries exceeded with url: /lsdy (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd6050>: Failed to resolve 'lsdy.clearto.cc' ([Errno -2] Name or service not known)""))"
http://beautyandbeast.link/api/v1/client/subscribe?token=09efec601852becb0079bb36a3a3159e,0,成功,
https://alink123.com/api/v1/client/subscribe?token=90efa2140dbb1e11e063829cc3286435,0,成功,
https://api.quickgosubapi.net/api/v1/client/subscribe?token=0e704cccbe742e3f1150f0082fcb7f19,0,失败,"请求失败: HTTPSConnectionPool(host='api.quickgosubapi.net', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=0e704cccbe742e3f1150f0082fcb7f19 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd48e0>: Failed to resolve 'api.quickgosubapi.net' ([Errno -2] Name or service not known)""))"
http://vpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=bb05f9ea73561817417629cbcadf538c,0,失败,请求失败: 404 Client Error: Not Found for url: http://vpn.gougouvpn.xyz:88/api/v1/client/subscribe?token=bb05f9ea73561817417629cbcadf538c
https://aaaa.gay/link/Sysp0FGZIaD96MzB?client=v2,0,失败,内容过短
http://xsj520.top/api/v1/client/subscribe?token=fa89816170530371f1ece408222e3f18,0,失败,"请求失败: HTTPConnectionPool(host='xsj520.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=fa89816170530371f1ece408222e3f18 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b83d7460>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://1yuanfly.live/link/BFf0B1neSZabeYIK?sub=3,0,失败,"请求失败: HTTPSConnectionPool(host='1yuanfly.live', port=443): Max retries exceeded with url: /link/BFf0B1neSZabeYIK?sub=3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8e73040>: Failed to resolve '1yuanfly.live' ([Errno -2] Name or service not known)""))"
http://free.ninecloud.co/api/v1/client/subscribe?token=7a3521e20fdc2a061a52578366ae975b,0,失败,请求失败: 530 Server Error:  for url: http://free.ninecloud.co/api/v1/client/subscribe?token=7a3521e20fdc2a061a52578366ae975b
https://aiosjhdy.forbit-api.boats/sub?token=f96eb57d5d748278a14faacb1347419e,0,失败,"请求失败: HTTPSConnectionPool(host='aiosjhdy.forbit-api.boats', port=443): Max retries exceeded with url: /sub?token=f96eb57d5d748278a14faacb1347419e (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4be0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://sub.hkaa0.ml/sub,0,失败,"请求失败: HTTPConnectionPool(host='sub.hkaa0.ml', port=80): Max retries exceeded with url: /sub (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd6a10>: Failed to resolve 'sub.hkaa0.ml' ([Errno -2] Name or service not known)""))"
https://api.eejsq.org/api/v1/client/subscribe?token=192e8020494866c944288dcd3835b1de,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.ejiasu.net/api/v1/client/subscribe?token=192e8020494866c944288dcd3835b1de
http://sub.sihaiyun.vip/api/v1/client/subscribe?token=cd7d7ca10baeffae792bdae5f964a52b&amp;flag=clash,0,失败,"请求失败: HTTPConnectionPool(host='sub.sihaiyun.vip', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=cd7d7ca10baeffae792bdae5f964a52b&amp;flag=clash (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8dd7bb0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://159.75.130.241/easynet/api/v1/client/subscribe?token=5c77bd133efdcceb5220ffba7d9cc544,0,失败,"请求失败: HTTPSConnectionPool(host='159.75.130.241', port=443): Max retries exceeded with url: /easynet/api/v1/client/subscribe?token=5c77bd133efdcceb5220ffba7d9cc544 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7d60>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://app.jisovpn.site/api/v1/client/subscribe?token=5d2f12c9211d3c62d9cfe6360f4da146#9itrguit,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5d2f12c9211d3c62d9cfe6360f4da146 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cd870>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
https://12123.org/api/v1/client/subscribe?token=758b131f7985f3fd39552d9893e579cc,0,失败,内容过短
https://1a1fe884-ae3c-3610-8075-cb778431f722.subdog.cyou/link/0S5cQlCnEuxrCBWZ?sub=3,0,成功,
https://api1.441166.xyz/api/v1/client/subscribe?token=e5650069f2235b67f5dd349969788b6d,0,失败,"请求失败: HTTPSConnectionPool(host='api1.441166.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e5650069f2235b67f5dd349969788b6d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd41c0>: Failed to resolve 'api1.441166.xyz' ([Errno -2] Name or service not known)""))"
https://123abc.love/api/v1/client/subscribe?token=5a546403da530d13dcf257a06d272516,0,失败,"请求失败: HTTPSConnectionPool(host='123abc.love', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5a546403da530d13dcf257a06d272516 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd6110>: Failed to resolve '123abc.love' ([Errno -2] Name or service not known)""))"
https://api.xinyo.vip/api/v1/client/subscribe?token=32766ad77e22239683fc3b9e2a06f4bd,2,成功,
https://20240913.sux.lol/api/v1/client/subscribe?token=c8c33b4171c2ac16631a191d5a19f6fe&amp;flag=meta,0,失败,"请求失败: HTTPSConnectionPool(host='20240913.sux.lol', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c8c33b4171c2ac16631a191d5a19f6fe&amp;flag=meta (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7430>: Failed to resolve '20240913.sux.lol' ([Errno -2] Name or service not known)""))"
http://www.a100.sbs/api/v1/client/subscribe?token=58c86f25d9057058d53ccecedb7af23b,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ww38.a100.sbs/api/v1/client/subscribe?token=58c86f25d9057058d53ccecedb7af23b
https://api.xqc.best/api/v1/client/subscribe?token=e6ad8b253dcb7df6e2cfefcd6b82f148,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e6ad8b253dcb7df6e2cfefcd6b82f148 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://sub.jarvistech.club/api/v1/client/subscribe?token=c13b020e973ddf7d94fcb2e8a93b15ac,0,成功,
https://7jyrf.no-mad-world.club/link/Xu9nuPVgUp0EcXR3?clash=3&amp;extend=1,0,失败,请求失败: 404 Client Error: Not Found for url: https://7jyrf.no-mad-world.club/link/Xu9nuPVgUp0EcXR3?clash=3&amp;extend=1
https://api.pay.pm/api/v1/link/sip002?token=d2bsXuU54Xqbf87W,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ww38.api.pay.pm/api/v1/link/sip002?token=d2bsXuU54Xqbf87W
https://api.ndsxfkjfvhzdsfio.quest/link/5RmR9YAnp0fgFUhc?clash=3,0,失败,请求失败: 404 Client Error: Not Found for url: https://api.ndsxfkjfvhzdsfio.quest/link/5RmR9YAnp0fgFUhc?clash=3
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;amp;amp;flag=clash,0,成功,
http://fdgdr0dg3.xbvpn.vip/api/v1/client/subscribe?token=49629c746a96cb7b4eadcde75cf19bce,0,失败,"请求失败: HTTPConnectionPool(host='fdgdr0dg3.xbvpn.vip', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=49629c746a96cb7b4eadcde75cf19bce (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd6590>: Failed to resolve 'fdgdr0dg3.xbvpn.vip' ([Errno -2] Name or service not known)""))"
https://api.mudidi1.win/api/v1/client/subscribe?token=70d0412cc843a15eabb72bedad2742da,0,失败,"请求失败: HTTPSConnectionPool(host='api.mudidi1.win', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=70d0412cc843a15eabb72bedad2742da (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd74c0>: Failed to resolve 'api.mudidi1.win' ([Errno -2] Name or service not known)""))"
http://d.xyss.xyz/link/OeM5KzbUvT0eMPYy?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='d.xyss.xyz', port=80): Max retries exceeded with url: /link/OeM5KzbUvT0eMPYy?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd6b60>: Failed to resolve 'd.xyss.xyz' ([Errno -2] Name or service not known)""))"
https://9lkyfh.babaivip.top/api/v1/client/subscribe?token=0631b0e70e123fd5c1bb9ff2bff2cda6,5,成功,
https://135841.xyz/api/v1/client/subscribe?token=226d2b4daee71f1f31df08d549d09394,0,失败,"请求失败: HTTPSConnectionPool(host='135841.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=226d2b4daee71f1f31df08d549d09394 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1017)')))"
https://api.xn--94q57lcvpw50b.com/api/v1/client/subscribe?token=a295e990c1d1e29e5289b5969d059135,0,失败,"请求失败: HTTPSConnectionPool(host='%e5%85%8d%e8%b4%b9%e6%9c%ba%e5%9c%ba.com', port=443): Max retries exceeded with url: /?token=a295e990c1d1e29e5289b5969d059135 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7280>: Failed to resolve '%e5%85%8d%e8%b4%b9%e6%9c%ba%e5%9c%ba.com' ([Errno -2] Name or service not known)""))"
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=6ea1bb60db4923beb1bb0214524aa652,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=6ea1bb60db4923beb1bb0214524aa652 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://7.wsub1103.lol/api/v1/client/subscribe?token=2c2fb9d9c9296ec4dc12409a1e452900,0,失败,请求失败: 403 Client Error: Forbidden for url: https://7.wsub1103.lol/api/v1/client/subscribe?token=2c2fb9d9c9296ec4dc12409a1e452900
http://fbapiv1.fbsublink.com/flydsubal/kihbzgttx4myazmj?sub=2&amp;extend=1,0,失败,内容过短
https://711.886511.xyz/api/v1/client/subscribe?token=86791c2550feb8827087de9743e3523e,0,失败,"请求失败: HTTPSConnectionPool(host='711.886511.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=86791c2550feb8827087de9743e3523e (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7190>: Failed to resolve '711.886511.xyz' ([Errno -2] Name or service not known)""))"
http://hpyjc.top/api/v1/client/subscribe?token=c049fc3a4590aec7bd7fc03f3048829b,0,成功,
https://aini.200566.xyz/share/col/tzjz66?token=FfSNFoxbwy8AxEHG4DU_p,0,失败,"请求失败: HTTPSConnectionPool(host='aini.200566.xyz', port=443): Max retries exceeded with url: /share/col/tzjz66?token=FfSNFoxbwy8AxEHG4DU_p (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd6230>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://wy.hkaa0.top/sub,0,失败,请求失败: 403 Client Error: Forbidden for url: https://wy.hkaa0.top/sub
http://www.nicevpns.com/api/v1/client/subscribe?token=5b56399d0e8946e3f28d5c8ef296527c,0,成功,
http://user.tsunaminet.cc/api/v1/client/subscribe?token=4f287360004d62858f581a784ef82282,0,成功,
http://api.wtcloud.xyz/api/v1/client/subscribe?token=3fb699fcf8fbbee5765592257f07623a,0,失败,"请求失败: HTTPConnectionPool(host='api.wtcloud.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=3fb699fcf8fbbee5765592257f07623a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd7790>: Failed to resolve 'api.wtcloud.xyz' ([Errno -2] Name or service not known)""))"
https://52pokemon.xz61.cn/api/v1/client/subscribe?token=70c4f57a9a11a006893cdd46a40861fe,0,失败,内容过短
http://dy.2983839.xyz/api/v1/client/subscribe?token=b87c66287336cd6ef695a3f675a895cb,0,失败,"请求失败: HTTPConnectionPool(host='dy.2983839.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=b87c66287336cd6ef695a3f675a895cb (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4cb1cfdf0>: Failed to resolve 'dy.2983839.xyz' ([Errno -2] Name or service not known)""))"
https://app.cloudlion.me/api/v1/client/subscribe?token=c0893ab776d761f1b351b3e7e5cd366c&amp;flag=clash,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=c0893ab776d761f1b351b3e7e5cd366c&amp;flag=clash
https://abyssvpnya.net/api/v1/client/subscribe?token=a07593e9c6c675db29babf0357d8dccf,0,失败,"请求失败: HTTPSConnectionPool(host='abyssvpnya.net', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a07593e9c6c675db29babf0357d8dccf (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7dc0>: Failed to resolve 'abyssvpnya.net' ([Errno -5] No address associated with hostname)""))"
http://mine.subcsyun.online/api/v1/client/subscribe?token=3a6be87e843fc485455b28d116ecaab3,0,成功,
http://dy.hpyjc.top/api/v1/client/subscribe?token=8cae880911989d6244ee7d24d400dabc,0,成功,
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=5656a7a3e1b5131b4b80d1690c845bec,0,成功,
http://173.249.198.78/api/v1/client/subscribe?token=64242973280bf51a044f6d2b3576788f,0,失败,请求超时
https://1yuanfly.live/link/BFf0B1neSZabeYIK?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='1yuanfly.live', port=443): Max retries exceeded with url: /link/BFf0B1neSZabeYIK?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd6bc0>: Failed to resolve '1yuanfly.live' ([Errno -2] Name or service not known)""))"
https://6yb3xq.dness.top/api/v1/client/subscribe?token=806af1bab2cc27eb02c2cf9ec1e9f7b9,6,成功,
https://api.abyssyun.top/api/v1/client/subscribe?token=926435ddf26a778b02263cf41807408b,0,成功,
https://aa.dabai.in/link/6hqEY4qjCts48S3y?sub=3,2,成功,
https://api.ktcat.online/ktcat?token=ba53b9678b3b53b03041bfec7888bd62,0,失败,"请求失败: HTTPSConnectionPool(host='api.ktcat.online', port=443): Max retries exceeded with url: /ktcat?token=ba53b9678b3b53b03041bfec7888bd62 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd5c60>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
https://apiv1.v27qae.com/flydsubal/esmjkbggec4shgmp?clash=1,0,失败,内容过短
https://api1.441166.xyz/api/v1/client/subscribe?token=d969bd19819e8c532823db4768d27dec,0,失败,"请求失败: HTTPSConnectionPool(host='api1.441166.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d969bd19819e8c532823db4768d27dec (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd42e0>: Failed to resolve 'api1.441166.xyz' ([Errno -2] Name or service not known)""))"
https://78fb170a-8f5c-46e9-991c-2b12fe04c1d1.xn--mes358a.art/api/v1/client/subscribe?token=35d1c267f8923dd26e4242ef4e706687,0,失败,"请求失败: HTTPSConnectionPool(host='78fb170a-8f5c-46e9-991c-2b12fe04c1d1.xn--mes358a.art', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=35d1c267f8923dd26e4242ef4e706687 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7940>: Failed to resolve '78fb170a-8f5c-46e9-991c-2b12fe04c1d1.xn--mes358a.art' ([Errno -2] Name or service not known)""))"
http://dydz.xn--mesv8bx6xtx3b.com:2006/api/v1/client/subscribe?token=e6763082d153dd317990382143d7b34f,0,失败,"请求失败: HTTPConnectionPool(host='dydz.xn--mesv8bx6xtx3b.com', port=2006): Max retries exceeded with url: /api/v1/client/subscribe?token=e6763082d153dd317990382143d7b34f (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8dd6ec0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://af078381-fcf9-457a-b03a-7bfaf506cd0b.xn--l6qx3lcvp58x.com/api/v1/client/subscribe?token=536c81b786085e0e5270db4185d21036,4,成功,
https://1g.gay/?v2b=www.yongdong.xyz,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=www.yongdong.xyz (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7820>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
http://fs123121.cdn.22.jiacdnd123456789.com/answer/land?token=14532fd5acaa9762fa4d1f09aaf5e07e,0,失败,"请求失败: HTTPConnectionPool(host='fs123121.cdn.22.jiacdnd123456789.com', port=80): Max retries exceeded with url: /answer/land?token=14532fd5acaa9762fa4d1f09aaf5e07e (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8e73e50>: Failed to resolve 'fs123121.cdn.22.jiacdnd123456789.com' ([Errno -2] Name or service not known)""))"
https://airport.raloar.top/api/v1/client/subscribe?token=f6f95acd161b7e014c074dee0135d323&amp;flag=meta,0,失败,"请求失败: HTTPSConnectionPool(host='airport.raloar.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f6f95acd161b7e014c074dee0135d323&amp;flag=meta (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd5630>: Failed to resolve 'airport.raloar.top' ([Errno -2] Name or service not known)""))"
http://dd.cxld.sbs/api/v1/client/subscribe?token=6773b6a8b81a0d64480b93d4579eb3cc,0,失败,"请求失败: HTTPConnectionPool(host='dd.cxld.sbs', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=6773b6a8b81a0d64480b93d4579eb3cc (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4cb1cfcd0>: Failed to resolve 'dd.cxld.sbs' ([Errno -2] Name or service not known)""))"
http://lumine.sumeru.design/?name=pmn.base64,0,失败,"请求失败: HTTPConnectionPool(host='lumine.sumeru.design', port=80): Max retries exceeded with url: /?name=pmn.base64 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8e38730>: Failed to resolve 'lumine.sumeru.design' ([Errno -2] Name or service not known)""))"
http://dy.luoxin.fun/link/fjXtAlrVzF54ghEj?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='dy.luoxin.fun', port=80): Max retries exceeded with url: /link/fjXtAlrVzF54ghEj?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd4580>: Failed to resolve 'dy.luoxin.fun' ([Errno -2] Name or service not known)""))"
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=5524b09a0c31c745b208a95daa2fc1f5,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5524b09a0c31c745b208a95daa2fc1f5 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://0b96e976-9ec3-44c0-aa2b-30bf8b0792ea.com/api/v1/client/subscribe?token=7e22d54bf813350a216f444453a7dbb4,112,成功,
https://app.legeth.cc/api/v1/client/subscribe?token=81452c2e31321c3a1b9945744ff97a91,0,失败,"请求失败: HTTPSConnectionPool(host='app.legeth.cc', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=81452c2e31321c3a1b9945744ff97a91 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4490>: Failed to resolve 'app.legeth.cc' ([Errno -2] Name or service not known)""))"
https://1g.gay/?v2b=www.jjyhk.com,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=www.jjyhk.com (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7880>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
https://1g.gay/?v2b=www.1jichang.xyz,0,失败,"请求失败: HTTPSConnectionPool(host='1g.gay', port=443): Max retries exceeded with url: /?v2b=www.1jichang.xyz (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4a90>: Failed to resolve '1g.gay' ([Errno -2] Name or service not known)""))"
https://569cdn.1010520.click/api/v1/client/subscribe?token=2af75f7c27dfa0e5aa175c7c64c01f28,0,失败,内容过短
http://gbtgurl01.org/api/v1/client/subscribe?token=36e8a67632a8d0f0c0eea58b099a0826,0,失败,内容过短
http://nangang.pro/api/v1/client/subscribe?token=4a1a9bb3c62ab962328265f71397a138,0,失败,"请求失败: HTTPConnectionPool(host='nangang.pro', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4a1a9bb3c62ab962328265f71397a138 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd4b20>: Failed to resolve 'nangang.pro' ([Errno -2] Name or service not known)""))"
http://clash77.top/api/v1/client/subscribe?token=c2587d668e9c3b1a0ebb9f121ee5307a,0,失败,"请求失败: HTTPConnectionPool(host='clash77.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c2587d668e9c3b1a0ebb9f121ee5307a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8e735e0>: Failed to resolve 'clash77.top' ([Errno -2] Name or service not known)""))"
http://g3i.buzz/v3/subscr?id=80bc8b9f7cf643e5b0f2b90a048d8ce5,0,失败,内容过短
https://admin.xn--iiq451n.com/api/v1/client/55d03c3072db6f91b7468f06106bace9,0,失败,请求失败: 403 Client Error: Forbidden for url: https://admin.xn--iiq451n.com/api/v1/client/55d03c3072db6f91b7468f06106bace9
http://laobideng.xyz/api/v1/client/subscribe?token=7343ee75e523a03eb9e20206a505d8fe,0,成功,
https://api.misakanet.buzz/api/v1/client/subscribe?token=700ea9d57578b12746619e3f55117bfa,0,失败,"请求失败: HTTPSConnectionPool(host='api.misakanet.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=700ea9d57578b12746619e3f55117bfa (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd5ba0>: Failed to resolve 'api.misakanet.buzz' ([Errno -2] Name or service not known)""))"
http://763352.top/api/v1/client/subscribe?token=3c6f91b0cfc25b391b0a9e9a8d22aeba,0,失败,"请求失败: HTTPConnectionPool(host='763352.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=3c6f91b0cfc25b391b0a9e9a8d22aeba (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8e391b0>: Failed to resolve '763352.top' ([Errno -2] Name or service not known)""))"
http://tg.cyy200.xyz/api/v1/client/subscribe?token=0a2611af2e3d8fea923fb41364aef006,0,失败,"请求失败: HTTPConnectionPool(host='tg.cyy200.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=0a2611af2e3d8fea923fb41364aef006 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4cb1cd810>: Failed to resolve 'tg.cyy200.xyz' ([Errno -2] Name or service not known)""))"
https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=a91422a7f63f828a453c1a9345348679,0,失败,请求失败: 403 Client Error: Forbidden for url: https://9527.bigbigwatermelon.com/api/v1/client/subscribe?token=a91422a7f63f828a453c1a9345348679
http://python-2pb1kf.chbk.run/sip002/sub,0,失败,请求超时
https://api.xqc.best/api/v1/client/subscribe?token=ea4f537a983f28cc318f81fd445709b6,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=ea4f537a983f28cc318f81fd445709b6 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://apopcloud.com/api/v1/client/subscribe?token=59a05360dc958a29e465b0cc7a1e32b8,0,成功,
https://774.gs/KKuPU,0,成功,
https://aiosjhdy.forbit-api.boats/sub?token=753a58cc961f624ad8001d00a73f5b28,0,失败,"请求失败: HTTPSConnectionPool(host='aiosjhdy.forbit-api.boats', port=443): Max retries exceeded with url: /sub?token=753a58cc961f624ad8001d00a73f5b28 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd70a0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://api.xinyo.vip/api/v1/client/subscribe?token=bb57e2195a6cabe24ed9469b3669aa0d,2,成功,
https://a.suixincloud.top/api/v1/client/subscribe?token=c331b8ec44eefe17f6cdfb36d3dc8df3,0,失败,"请求失败: HTTPSConnectionPool(host='a.suixincloud.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c331b8ec44eefe17f6cdfb36d3dc8df3 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd6d10>: Failed to resolve 'a.suixincloud.top' ([Errno -3] Temporary failure in name resolution)""))"
https://apinainiucloud.lat/api/v1/client/subscribe?token=cfd29507cc1e7e7a6f303e7a7d87a3af,0,失败,"请求失败: HTTPSConnectionPool(host='apinainiucloud.lat', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=cfd29507cc1e7e7a6f303e7a7d87a3af (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4820>: Failed to resolve 'apinainiucloud.lat' ([Errno -2] Name or service not known)""))"
http://hazz.win/j7K6wN,0,失败,内容过短
http://v2.jsyml.cn/api/v1/client/subscribe?token=4a30e8b42556645d7bc795a448fbf908&amp;amp;flag=clash,0,失败,"请求失败: HTTPConnectionPool(host='v2.jsyml.cn', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4a30e8b42556645d7bc795a448fbf908&amp;amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8e3a9e0>: Failed to resolve 'v2.jsyml.cn' ([Errno -5] No address associated with hostname)""))"
https://a2673b60-aca1-48c2-a4ad-abeb518e18f9.fengchenginx.com/api/v1/client/subscribe?token=5545a2ce2b4ae32422112393c0a68a7f,0,失败,"请求失败: HTTPSConnectionPool(host='a2673b60-aca1-48c2-a4ad-abeb518e18f9.fengchenginx.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=5545a2ce2b4ae32422112393c0a68a7f (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4160>: Failed to resolve 'a2673b60-aca1-48c2-a4ad-abeb518e18f9.fengchenginx.com' ([Errno -2] Name or service not known)""))"
http://filusdt.461553.best:1588/api/v1/client/subscribe?token=9acba0c4ee1365037688fa1aebaf20cf,0,失败,内容过短
http://6b.zhunchuanpb.com/api/v1/client/subscribe?token=4e535a0fa62acb50f2fda66a8d48e8ed,0,失败,请求失败: 403 Client Error: Forbidden for url: http://6b.zhunchuanpb.com/api/v1/client/subscribe?token=4e535a0fa62acb50f2fda66a8d48e8ed
http://subs.202218.xyz/link/vf66JsLdkIGf7304?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/vf66JsLdkIGf7304?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8dd4fa0>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
http://199.245.100.6:8080/s/mkum29,0,失败,请求超时
https://api.prprcloud.life/ss/6605/3rDRpfqqnQ/,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://api.prprcloud.life/ss/6605/3rDRpfqqnQ/
https://api.jijio.cloud/api/v1/client/subscribe?token=0953ffb7522c9e2bf6eb4d93f41dba58,0,成功,
https://52pokemon.xz61.cn/api/v1/client/subscribe?token=c3f47e3befd82b7894e11a50b5a1fdb7,0,失败,内容过短
https://api.xn--yfr72t8r4bvhd.xyz/api/v1/client/subscribe?token=3aa427960573c7bf8817bfb51cadca93,0,失败,"请求失败: HTTPSConnectionPool(host='api.xn--yfr72t8r4bvhd.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3aa427960573c7bf8817bfb51cadca93 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8e39b10>: Failed to resolve 'api.xn--yfr72t8r4bvhd.xyz' ([Errno -3] Temporary failure in name resolution)""))"
https://99ding.men/api/v1/client/subscribe?token=17281be6336062b0ada04b51d8ac535a,0,失败,请求失败: 522 Server Error: <none> for url: https://99ding.men/api/v1/client/subscribe?token=17281be6336062b0ada04b51d8ac535a
https://apopcloud.com/api/v1/client/subscribe?token=850fbdd7e63542f3ad53a83028f10904,0,成功,
https://airtcplink3.top/link/Lg9hIf8xhN4NXdgJ?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='airtcplink3.top', port=443): Max retries exceeded with url: /link/Lg9hIf8xhN4NXdgJ?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd6f80>: Failed to resolve 'airtcplink3.top' ([Errno -2] Name or service not known)""))"
https://apps.airfree.cloud/link/28ef6da76a3b0a8e?clash=1,0,失败,请求失败: 522 Server Error: <none> for url: https://apps.airfree.cloud/link/28ef6da76a3b0a8e?clash=1
https://air.nicetive.site/api/v1/client/subscribe?token=a124f38f90d8cf695bf625baa5f52491,0,失败,"请求失败: HTTPSConnectionPool(host='air.nicetive.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=a124f38f90d8cf695bf625baa5f52491 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd41c0>: Failed to resolve 'air.nicetive.site' ([Errno -2] Name or service not known)""))"
https://0cd372a8-ef9b-33f6-b85a-a805a910bf43.subdotu.com/link/ThV2b4awQHcWJbSx?clash=1,0,失败,"请求失败: HTTPSConnectionPool(host='0cd372a8-ef9b-33f6-b85a-a805a910bf43.subdotu.com', port=443): Max retries exceeded with url: /link/ThV2b4awQHcWJbSx?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cf790>: Failed to resolve '0cd372a8-ef9b-33f6-b85a-a805a910bf43.subdotu.com' ([Errno -2] Name or service not known)""))"
https://api.xjichang.buzz/api/v1/client/subscribe?token=498eacc0363916b333332febff93b66d,0,失败,"请求失败: HTTPSConnectionPool(host='api.xjichang.buzz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=498eacc0363916b333332febff93b66d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8e73400>: Failed to resolve 'api.xjichang.buzz' ([Errno -2] Name or service not known)""))"
https://20240802.canadapost-vip.com/api/v1/client/subscribe?token=2bc2dbcc729c0096ef6d064a3d01029c,0,失败,"请求失败: HTTPSConnectionPool(host='20240802.canadapost-vip.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=2bc2dbcc729c0096ef6d064a3d01029c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd4610>: Failed to resolve '20240802.canadapost-vip.com' ([Errno -2] Name or service not known)""))"
https://app.legeth.cc/api/v1/client/subscribe?token=b5b295500eedd5057b04df3efa110343,0,失败,"请求失败: HTTPSConnectionPool(host='app.legeth.cc', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=b5b295500eedd5057b04df3efa110343 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8dd7520>: Failed to resolve 'app.legeth.cc' ([Errno -2] Name or service not known)""))"
https://12123.org/api/v1/client/subscribe?token=64c27e6ab2ac2f4b4629dcbd39c93556,0,失败,内容过短
http://python-2pb1kf.chbk.run/ssr/sub,0,失败,请求超时
https://18.laomao1.xyz/api/v1/client/subscribe?token=275908c8f75844584ab109d4e140dd82,0,失败,"请求失败: HTTPSConnectionPool(host='18.laomao1.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=275908c8f75844584ab109d4e140dd82 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4cb1cfbb0>: Failed to resolve '18.laomao1.xyz' ([Errno -2] Name or service not known)""))"
http://em7.buzz/v3/subscr?id=5359840131e14ce3bb2e6c00a8fc3e01,0,失败,内容过短
https://a.jiedianxielou.workers.dev/api/v1/client/subscribe?token=UjBGOXVrdFBKYzlvNDRsNHQ4eUVzTVZzSnBRZng5Z003UjVranR2RTJIeUJqQTlHUlgxWTdEaWdiSmJJemxPdHBCeEs1VFhrMFlKNjBYblRxTDBhQ1RPYkdWU20vdXJXQUMyd2lISW5ZRmUxUWNoV0NOUlZDMGc9,7,成功,
https://231787.xyz/api/v1/client/subscribe?token=9320d6e9bc007dd0dd0c2cfc89acd910,0,失败,内容过短
https://api2.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=b0b61433d831d4fed2af6eafc28c64db,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api2.xn--bnq37rc0nw50b.com/api/v1/client/subscribe?token=b0b61433d831d4fed2af6eafc28c64db
http://fs123121.cdn.22.jiacdnd123456789.com/answer/land?token=4b64a6d4d720c34d84a19e91f3c3aba4,0,失败,"请求失败: HTTPConnectionPool(host='fs123121.cdn.22.jiacdnd123456789.com', port=80): Max retries exceeded with url: /answer/land?token=4b64a6d4d720c34d84a19e91f3c3aba4 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf12bc0>: Failed to resolve 'fs123121.cdn.22.jiacdnd123456789.com' ([Errno -2] Name or service not known)""))"
http://6bsub.zhunchuanpb.com/api/v1/client/subscribe?token=16023278f7dd0a98aa927bf2648b6a7c,0,失败,"请求失败: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))"
https://911tg3rs.com/api/v1/client/subscribe?token=1b2bbf02dcccacf428d3ad41573ad16e,0,失败,内容过短
http://j2s.buzz/v3/subscr?id=2119a8ea90154a2abf12f5eb0425daf7,0,失败,内容过短
http://subs.202218.xyz/link/UcQyT7N3UAPJUibQ?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/UcQyT7N3UAPJUibQ?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf13fa0>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
http://service-n1e0wv40-1305719984.gz.apigw.tencentcs.com/link/lgz5t0dsywxqvswu?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='service-n1e0wv40-1305719984.gz.apigw.tencentcs.com', port=80): Max retries exceeded with url: /link/lgz5t0dsywxqvswu?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf13130>: Failed to resolve 'service-n1e0wv40-1305719984.gz.apigw.tencentcs.com' ([Errno -5] No address associated with hostname)""))"
https://30388d70-6f5c-4d7c-8daa-9d3df7c5c526.9150e878-8296-4798-a172-c3fe66b8dee5.ddnsgeek.com/peqi.efrainpackqs2584.workers.dev/630257ce-cc6f-42ca-b908-67a0ca6b1268?clash,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://30388d70-6f5c-4d7c-8daa-9d3df7c5c526.9150e878-8296-4798-a172-c3fe66b8dee5.ddnsgeek.com/peqi.efrainpackqs2584.workers.dev/630257ce-cc6f-42ca-b908-67a0ca6b1268?clash
http://ya555.top/api/v1/client/subscribe?token=0a84599d2358d2488d0d5d625e8878c5,0,失败,"请求失败: HTTPConnectionPool(host='ya555.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=0a84599d2358d2488d0d5d625e8878c5 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbfa1360>: Failed to resolve 'ya555.top' ([Errno -2] Name or service not known)""))"
https://api.xinyo.vip/api/v1/client/subscribe?token=b0e5f918cf3c088dcfa65bf1f0a40ba1,2,成功,
http://188.213.196.100:8585/clash/proxies,0,失败,"请求失败: HTTPConnectionPool(host='188.213.196.100', port=8585): Max retries exceeded with url: /clash/proxies (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf10c40>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://apps.apple.com/us/app/karing/id6472431552,6,成功,
http://106.15.63.84:39391/api/zhiji?token=0664a43b53a5108499d36ae1357b8079,0,失败,请求超时
http://app.xn--cloud-et5i500m.biz/api/v1/client/subscribe?token=887fd522ea50aa0cf89cea303812d908,0,失败,"请求失败: HTTPConnectionPool(host='app.xn--cloud-et5i500m.biz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=887fd522ea50aa0cf89cea303812d908 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf11900>: Failed to resolve 'app.xn--cloud-et5i500m.biz' ([Errno -2] Name or service not known)""))"
https://api.prprcloud.life/ss/7742/thQtcqKOT5/,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://api.prprcloud.life/ss/7742/thQtcqKOT5/
http://gbtgurl01.org/api/v1/client/subscribe?token=226a53fee41ab0c266c52769e9e8cd10,0,失败,内容过短
http://66ds.dishujichang.xyz/api/v1/client/subscribe?token=22d16f00edb53675927fe96093c7af1a,0,失败,请求失败: 404 Client Error: Not Found for url: http://66ds.dishujichang.xyz/api/v1/client/subscribe?token=22d16f00edb53675927fe96093c7af1a
http://www.chachajichang.top/api/v1/client/subscribe?token=a34e167f6620fbfc6d2e533913e4078f,0,成功,
http://2ec535a5c35aa5a4b44249428dbb3d01.52pokemon.top/api/v1/client/subscribe?token=8cf0a4fe2c5e35887a50677c2f79325b,0,失败,"请求失败: HTTPConnectionPool(host='2ec535a5c35aa5a4b44249428dbb3d01.52pokemon.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8cf0a4fe2c5e35887a50677c2f79325b (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf13610>: Failed to resolve '2ec535a5c35aa5a4b44249428dbb3d01.52pokemon.top' ([Errno -2] Name or service not known)""))"
https://app.jisovpn.site/api/v1/client/subscribe?token=b87afe5c85c59f422ded2956e53ebdc5,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=b87afe5c85c59f422ded2956e53ebdc5 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbfa0b20>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
https://api2.mbo-xxx.top/api/v1/client/subscribe?token=cfeb1ca75485fd3782480ebd2fbc53cd,0,失败,"请求失败: HTTPSConnectionPool(host='api2.mbo-xxx.top', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=cfeb1ca75485fd3782480ebd2fbc53cd (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf13c40>: Failed to resolve 'api2.mbo-xxx.top' ([Errno -2] Name or service not known)""))"
https://api.touhou.center/sub/a817a5effa9865af/clash,0,成功,
https://api.xqc.best/api/v1/client/subscribe?token=d2b3434d2072026c1f7553f5616f34c7,0,失败,"请求失败: HTTPSConnectionPool(host='api.xqc.best', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=d2b3434d2072026c1f7553f5616f34c7 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
https://41be350f-5079-4195-8329-f6fa25f9906a.com/api/v1/client/subscribe?token=62dce9ae4b03eace2f581dd8ea8fdd51,0,失败,"请求失败: HTTPSConnectionPool(host='41be350f-5079-4195-8329-f6fa25f9906a.com', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=62dce9ae4b03eace2f581dd8ea8fdd51 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b86c4190>: Failed to resolve '41be350f-5079-4195-8329-f6fa25f9906a.com' ([Errno -2] Name or service not known)""))"
https://789.st/RtvKWdJ,1,成功,
https://47.242.186.70/api/v1/client/subscribe?token=df57a404bcbd43c807d55f95377bb32a,0,失败,"请求失败: HTTPSConnectionPool(host='47.242.186.70', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=df57a404bcbd43c807d55f95377bb32a (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1017)')))"
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=a7962ebc48c9cee3571e63007a7acc1d&amp;flag=clash,0,成功,
https://51fan.one/api/v1/client/subscribe?token=a7e319a16ba047a8ff5c64f74ad68e5c,0,失败,请求失败: 403 Client Error: Forbidden for url: https://51fan.one/api/v1/client/subscribe?token=a7e319a16ba047a8ff5c64f74ad68e5c
http://33yun.xyz/api/v1/client/subscribe?token=c4a2f32dae35d056db29aed161e01338,0,失败,"请求失败: HTTPConnectionPool(host='33yun.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c4a2f32dae35d056db29aed161e01338 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf3e6b0>: Failed to resolve '33yun.xyz' ([Errno -2] Name or service not known)""))"
http://www.a100.sbs/api/v1/client/subscribe?token=0821c2f6504eaa53daa0dab61cbbd1c4,0,失败,请求失败: 403 Client Error: Forbidden for url: http://ww38.a100.sbs/api/v1/client/subscribe?token=0821c2f6504eaa53daa0dab61cbbd1c4
https://aiosjhdy.forbit-api.boats/sub?token=86a8e2d6851144a0840a82e8af47e6d9,0,失败,"请求失败: HTTPSConnectionPool(host='aiosjhdy.forbit-api.boats', port=443): Max retries exceeded with url: /sub?token=86a8e2d6851144a0840a82e8af47e6d9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4bbf3d4b0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://api.sub-300.club/link/Wo5Nrr0QWszb2wcw?clash=3&amp;extend=1,7,成功,
http://dishujichang.xyz/api/v1/client/subscribe?token=5b6bc131aeeccb53b207a69f78ce16be,0,失败,请求失败: 403 Client Error: Forbidden for url: http://dishujichang.xyz/api/v1/client/subscribe?token=5b6bc131aeeccb53b207a69f78ce16be
https://api.xfltd.xyz/api/v1/client/subscribe?token=1092a253b1def6495ba06d77006292f4,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xfltd.xyz/api/v1/client/subscribe?token=1092a253b1def6495ba06d77006292f4
https://api.hy2.lol/api/v1/client/subscribe?token=e09a714a3549b84fc448bfe3553b783d,0,失败,"请求失败: HTTPSConnectionPool(host='api.hy2.lol', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=e09a714a3549b84fc448bfe3553b783d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b887a9e0>: Failed to resolve 'api.hy2.lol' ([Errno -2] Name or service not known)""))"
http://subs.202218.xyz/link/englMGkJ2OVZvZeB?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/englMGkJ2OVZvZeB?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8333700>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://a.jiedianxielou.workers.dev/api/v1/client/subscribe?token=bHl6RldjV3draTAyMjlHSXR2VW9haFk0ZE9iNWQ3eTVyVEl5RjlqQWJLMlliY2NkQUxVcG5wemFKN0JEdjFsbTZKTzVvS1lvenVCMW9TQWZTcW8vWStWZ3VUQmF6anJwMksrbXloTGhWS25KRWY2cUFVWT0,7,成功,
https://a.aikllc.tech/api/v1/client/subscribe?token=9a6b1bf0dd3469fc0fe3bc79a2b0ba92,0,失败,"请求失败: HTTPSConnectionPool(host='a.aikllc.tech', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=9a6b1bf0dd3469fc0fe3bc79a2b0ba92 (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1017)')))"
http://jshou.top/api/v1/client/subscribe?token=c0780b5906963e16f201e6bbec50bd6a,0,失败,"请求失败: HTTPConnectionPool(host='jshou.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=c0780b5906963e16f201e6bbec50bd6a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8b4bdf0>: Failed to resolve 'jshou.top' ([Errno -5] No address associated with hostname)""))"
http://hpyjc.top/api/v1/client/subscribe?token=e49e20f28920511e029a02ff3acfd12a,0,成功,
https://a94d418e-1898-42df-bcf2-d970a5f3a939.mysubsoft.com/api/v1/client/subscribe?token=1cb8e0050af86604a7638c6c1a91e3f9,0,失败,请求失败: 522 Server Error: <none> for url: https://a94d418e-1898-42df-bcf2-d970a5f3a939.mysubsoft.com/api/v1/client/subscribe?token=1cb8e0050af86604a7638c6c1a91e3f9
https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=55829eb8e25c26ae742e5f54cd68dcb6&amp;flag=clashmeta,0,失败,请求失败: 403 Client Error: Forbidden for url: https://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=55829eb8e25c26ae742e5f54cd68dcb6&amp;flag=clashmeta
https://520748.xyz/api/v1/client/subscribe?token=f6373804a638a0432ee70adad2a357b1,0,失败,"请求失败: HTTPSConnectionPool(host='520748.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=f6373804a638a0432ee70adad2a357b1 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1ebf0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
http://em7.buzz/v3/subscr?id=377bf036b6b24867bf3adbeb24a90326,0,失败,内容过短
https://ap.niaodi.top/niao?token=cdaa1b1f44005a4ed020ea98e001d0c5,6,成功,
https://0415.chun-auto-one.xyz/api/v1/client/subscribe?token=fe4e2280fff38b11c2fc10ae725a753c,0,失败,"请求失败: HTTPSConnectionPool(host='0415.chun-auto-one.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=fe4e2280fff38b11c2fc10ae725a753c (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed9060>: Failed to resolve '0415.chun-auto-one.xyz' ([Errno -2] Name or service not known)""))"
https://api.akijp.tokyo/api/v1/client/subscribe?token=3406466eec3983e7f7d132c0995df8d4,0,失败,"请求失败: HTTPSConnectionPool(host='api.akijp.tokyo', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=3406466eec3983e7f7d132c0995df8d4 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8d1d630>: Failed to resolve 'api.akijp.tokyo' ([Errno -2] Name or service not known)""))"
http://dy.hpyjc.top/api/v1/client/subscribe?token=e49e20f28920511e029a02ff3acfd12a,0,成功,
https://api.dingyueddns.life/link/Z5wvm37wOATEUDoo?list=shadowrocket,0,失败,"请求失败: HTTPSConnectionPool(host='api.dingyueddns.life', port=443): Max retries exceeded with url: /link/Z5wvm37wOATEUDoo?list=shadowrocket (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4b8ed91b0>: Failed to resolve 'api.dingyueddns.life' ([Errno -2] Name or service not known)""))"
https://api.sub-200.club/link/KB1m4EHFEP4KbJLi?clash=3,7,成功,
http://v2.jsyml.cn/api/v1/client/subscribe?token=4a30e8b42556645d7bc795a448fbf908&amp;amp;amp;flag=clash,0,失败,"请求失败: HTTPConnectionPool(host='v2.jsyml.cn', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4a30e8b42556645d7bc795a448fbf908&amp;amp;amp;flag=clash (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8d1d660>: Failed to resolve 'v2.jsyml.cn' ([Errno -5] No address associated with hostname)""))"
http://kuaiyin.vip/link/yv43Htvo4kFTYZCy?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='kuaiyin.vip', port=80): Max retries exceeded with url: /link/yv43Htvo4kFTYZCy?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf82950>: Failed to resolve 'kuaiyin.vip' ([Errno -2] Name or service not known)""))"
https://app.cloudlion.me/api/v1/client/subscribe?token=273e3e69a066906f1eebe403686dd440,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=273e3e69a066906f1eebe403686dd440
http://www.leagueofheroes.ml/api/v1/client/subscribe?token=4a0e2a93a6329dc1a5323ca3f22afdcf,0,失败,"请求失败: HTTPConnectionPool(host='www.leagueofheroes.ml', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4a0e2a93a6329dc1a5323ca3f22afdcf (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf820b0>: Failed to resolve 'www.leagueofheroes.ml' ([Errno -2] Name or service not known)""))"
https://api.biqibao.site/api/v1/client/subscribe?token=b48f60a1bee6bd354ef6b28637ecc01c,0,成功,
http://s.33y.run/v3/subscr?id=70940ef0d98d475c8c4c359260f2eff2,0,失败,请求失败: 403 Client Error: Forbidden for url: https://s.33y.run/v3/subscr?id=70940ef0d98d475c8c4c359260f2eff2
http://www.mantou88.xyz/link/MZooMoON4bFPjoKA?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='www.mantou88.xyz', port=80): Max retries exceeded with url: /link/MZooMoON4bFPjoKA?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf81720>: Failed to resolve 'www.mantou88.xyz' ([Errno -2] Name or service not known)""))"
https://123abc.love/api/v1/client/subscribe?token=44d62cdfb55063181546800cc6d066ed,0,失败,"请求失败: HTTPSConnectionPool(host='123abc.love', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=44d62cdfb55063181546800cc6d066ed (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf81de0>: Failed to resolve '123abc.love' ([Errno -2] Name or service not known)""))"
https://acl.syyn.pw/api/v1/client/subscribe?token=50ec85cb5066c879d0413aa2650eee0b,0,失败,内容过短
https://app.jisovpn.site/api/v1/client/subscribe?token=b57605ca73be8d4d20d9e369720e17c0,0,失败,"请求失败: HTTPSConnectionPool(host='app.jisovpn.site', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=b57605ca73be8d4d20d9e369720e17c0 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf82ad0>: Failed to resolve 'app.jisovpn.site' ([Errno -2] Name or service not known)""))"
http://www.e300daniu.com/api/v1/client/subscribe?token=4048f46b23cadc60d0b735fb5976b4c0,0,失败,"请求失败: HTTPConnectionPool(host='www.e300daniu.com', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=4048f46b23cadc60d0b735fb5976b4c0 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db0100>: Failed to resolve 'www.e300daniu.com' ([Errno -5] No address associated with hostname)""))"
http://www.chachajichang.top/api/v1/client/subscribe?token=29f4fcbc7e2083073727ff1f8fe17136,0,成功,
http://0dianyun3.xyz/link/2IOkvjaIJwLILz8n?clash=1,0,失败,请求超时
http://laobideng.xyz/api/v1/client/subscribe?token=1a925b98f598b08035f819eeb6dbe6f1,0,成功,
https://4g.mkvn.net/api/v1/client/subscribe?token=d4b7daa53b8a2cf4c0d7c5c6d21d82b8,0,失败,请求失败: 521 Server Error: <none> for url: https://4g.mkvn.net/api/v1/client/subscribe?token=d4b7daa53b8a2cf4c0d7c5c6d21d82b8
https://15212712-20f5-40a5-b9aa-8363e0130171.ee137666-1e0a-46db-bbd6-cc18f9841234.accesscam.org/epeius-55o.pages.dev/gggg9990?clash,0,失败,请求失败: 500 Server Error: Internal Server Error for url: https://15212712-20f5-40a5-b9aa-8363e0130171.ee137666-1e0a-46db-bbd6-cc18f9841234.accesscam.org/epeius-55o.pages.dev/gggg9990?clash
http://66ds.dishujichang.xyz/api/v1/client/subscribe?token=b65f146b09c16e19fa0b2acc76f311e5,0,失败,请求失败: 404 Client Error: Not Found for url: http://66ds.dishujichang.xyz/api/v1/client/subscribe?token=b65f146b09c16e19fa0b2acc76f311e5
https://ae86.235999.xyz/api/v1/client/subscribe?token=fa36dcc907b77845036a428d093e450b,0,失败,"请求失败: HTTPSConnectionPool(host='ae86.235999.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=fa36dcc907b77845036a428d093e450b (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf821a0>: Failed to resolve 'ae86.235999.xyz' ([Errno -2] Name or service not known)""))"
http://hazz.win/7fpAcs,0,失败,内容过短
https://amatrixap.com/link/NggE8RCA4c87Cmze?sub=3,0,失败,请求失败: 403 Client Error: Forbidden for url: https://amatrixap.com/link/NggE8RCA4c87Cmze?sub=3
http://loving123.cloud/api/v1/client/subscribe?token=77a544908fcc64dd6959ec2d0cf5cf98,0,失败,"请求失败: HTTPConnectionPool(host='loving123.cloud', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=77a544908fcc64dd6959ec2d0cf5cf98 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf81a20>: Failed to resolve 'loving123.cloud' ([Errno -2] Name or service not known)""))"
https://app.gomeow.cloud/api/v1/client/subscribe?token=e338d7b14c8a8caf52e40c19fa63541a,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.gomeow.cloud/api/v1/client/subscribe?token=e338d7b14c8a8caf52e40c19fa63541a
https://app.cloudlion.me/api/v1/client/subscribe?token=d2f727d5245a198e520bb00a60803f78,0,失败,请求失败: 403 Client Error: Forbidden for url: https://app.cloudlion.me/api/v1/client/subscribe?token=d2f727d5245a198e520bb00a60803f78
http://3ae4349382d5ae35b6e5dda2e68d3df0.52pokemon.top/api/v1/client/subscribe?token=da65271ed77f83d7d6bf974f0fc82a05,0,失败,"请求失败: HTTPConnectionPool(host='3ae4349382d5ae35b6e5dda2e68d3df0.52pokemon.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=da65271ed77f83d7d6bf974f0fc82a05 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db2a70>: Failed to resolve '3ae4349382d5ae35b6e5dda2e68d3df0.52pokemon.top' ([Errno -2] Name or service not known)""))"
https://aicccc.top/kfjdj/9kx8dj27/kdjo1982/ksbxj9?token=ec0baced8ddd85f8e4a5a8076545f64d,0,失败,"请求失败: HTTPSConnectionPool(host='aicccc.top', port=443): Max retries exceeded with url: /kfjdj/9kx8dj27/kdjo1982/ksbxj9?token=ec0baced8ddd85f8e4a5a8076545f64d (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf80970>: Failed to resolve 'aicccc.top' ([Errno -2] Name or service not known)""))"
http://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=2dd7b0de39536f2e08d53d4bdf078c28,0,失败,请求失败: 403 Client Error: Forbidden for url: http://api.xn--14ra41gd24b.xyz/api/v1/client/subscribe?token=2dd7b0de39536f2e08d53d4bdf078c28
http://www.qianlong520.top/api/v1/client/subscribe?token=17363ae10e07f2af9cf9b40cb854fdc7,0,失败,"请求失败: HTTPConnectionPool(host='www.qianlong520.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=17363ae10e07f2af9cf9b40cb854fdc7 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db2ad0>: Failed to resolve 'www.qianlong520.top' ([Errno -2] Name or service not known)""))"
http://www.zhenyevpn.xyz/api/v1/client/subscribe?token=91f79925beaa75c98e0233c44ca31eab&amp;amp;amp;flag=clash,0,成功,
http://panda.xn--i8sx78aisa52z.com/api/v1/client/subscribe?token=9d6d1aac03e07c628b6dd4927a314be0,0,成功,
http://dingyue3.qyjc.xyz/api/v1/client/subscribe?token=e62a527fe908e7486693137f9f65174e,0,失败,"请求失败: HTTPConnectionPool(host='dingyue3.qyjc.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=e62a527fe908e7486693137f9f65174e (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b87ee6b0>: Failed to resolve 'dingyue3.qyjc.xyz' ([Errno -3] Temporary failure in name resolution)""))"
https://api.dingyueapi.win/api/v1/client/subscribe?token=455a303add84837b4518e9f49426aedb,0,失败,内容过短
http://python-2pb1kf.chbk.run/trojan/sub,0,失败,请求超时
https://api.fenghuolun.xyz/api/v1/client/subscribe?token=c097aa209f8544db707e0eeb6c497d28,0,失败,"请求失败: HTTPSConnectionPool(host='api.fenghuolun.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=c097aa209f8544db707e0eeb6c497d28 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate (_ssl.c:1017)')))"
http://s4.subcsyun.online/api/v1/client/subscribe?token=937cc32cb4f408c7a160bd0346f0c185,0,成功,
http://python-2pb1kf.chbk.run/clash/proxies,0,失败,请求超时
http://dy.changyouVPN.top/api/v1/client/subscribe?token=edd2107751aa28d4fa6506083f417b40,0,失败,内容过短
http://193.134.211.92/api/v1/client/subscribe?token=610ae34c5b3c47315ff00b281d8aee83,0,失败,"请求失败: HTTPConnectionPool(host='193.134.211.92', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=610ae34c5b3c47315ff00b281d8aee83 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4bbf802e0>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://vip2.xxyjc.xyz/link/D76Hux3wLGlh5eX5?sub=3,0,失败,内容过短
https://api.xn--yfr72t8r4bvhd.xyz/api/v1/client/subscribe?token=438609cffe3a51f5b30b7c8ca391ed04,0,失败,"请求失败: HTTPSConnectionPool(host='api.xn--yfr72t8r4bvhd.xyz', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=438609cffe3a51f5b30b7c8ca391ed04 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf80820>: Failed to resolve 'api.xn--yfr72t8r4bvhd.xyz' ([Errno -3] Temporary failure in name resolution)""))"
http://ya555.top/api/v1/client/subscribe?token=8e7bd7d4c221cceb2c1380d34ade3d24,0,失败,"请求失败: HTTPConnectionPool(host='ya555.top', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=8e7bd7d4c221cceb2c1380d34ade3d24 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db0be0>: Failed to resolve 'ya555.top' ([Errno -2] Name or service not known)""))"
http://188.213.196.100:8585/ssr/sub,0,失败,"请求失败: HTTPConnectionPool(host='188.213.196.100', port=8585): Max retries exceeded with url: /ssr/sub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8db0a00>: Failed to establish a new connection: [Errno 111] Connection refused'))"
https://aini.200566.xyz/tzjz55/download/%E5%8F%B0%E6%B9%BE%E8%87%AA%E5%BB%BA%E8%8A%82%E7%82%B9,0,失败,"请求失败: HTTPSConnectionPool(host='aini.200566.xyz', port=443): Max retries exceeded with url: /tzjz55/download/%E5%8F%B0%E6%B9%BE%E8%87%AA%E5%BB%BA%E8%8A%82%E7%82%B9 (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fb4b8db3250>: Failed to establish a new connection: [Errno 111] Connection refused'))"
http://subs.202218.xyz/link/XErYBuBXJv7GazMT?clash=1,0,失败,"请求失败: HTTPConnectionPool(host='subs.202218.xyz', port=80): Max retries exceeded with url: /link/XErYBuBXJv7GazMT?clash=1 (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4bbf80a30>: Failed to resolve 'subs.202218.xyz' ([Errno -2] Name or service not known)""))"
https://app.rookiebase.cn/api/v1/client/subscribe?token=98938a1f3be0083fa7dc78b9dd8476a0,0,失败,"请求失败: HTTPSConnectionPool(host='app.rookiebase.cn', port=443): Max retries exceeded with url: /api/v1/client/subscribe?token=98938a1f3be0083fa7dc78b9dd8476a0 (Caused by NameResolutionError(""<urllib3.connection.HTTPSConnection object at 0x7fb4bbf80df0>: Failed to resolve 'app.rookiebase.cn' ([Errno -2] Name or service not known)""))"
https://088ea81a-3547-85e0-4af6-dfcb3c6674aa.372372.xyz/api/v1/client/subscribe?token=91329feda803c29309d5eae3e2c9c004,0,失败,内容过短
https://aaaa.gay/link/dJIBd957Oj9xm334?client=v2,0,失败,内容过短
http://37.32.27.116:8080/vmess/sub,0,失败,请求超时
http://dingyue2.qyjc.xyz/api/v1/client/subscribe?token=55be191adc2c919537a823623bb1e02a,0,失败,"请求失败: HTTPConnectionPool(host='dingyue2.qyjc.xyz', port=80): Max retries exceeded with url: /api/v1/client/subscribe?token=55be191adc2c919537a823623bb1e02a (Caused by NameResolutionError(""<urllib3.connection.HTTPConnection object at 0x7fb4b8db2170>: Failed to resolve 'dingyue2.qyjc.xyz' ([Errno -3] Temporary failure in name resolution)""))"
http://42.51.33.241:88/api/v1/client/subscribe?token=13525cf326003059e1c06a4d40cc9cbb,0,失败,请求超时
http://39.106.12.141:8081/clash/proxies,0,失败,请求超时
http://173.249.198.78/api/v1/client/subscribe?token=1179d95eeb65c64866e8fbb8d9103595,0,失败,请求超时
http://1.1596666.xyz/api/v1/client/subscribe?token=ba7b1ba7d530350c25f13932267d272a,0,失败,请求超时
http://python-2pb1kf.chbk.run/vmess/sub,0,失败,"请求失败: HTTPConnectionPool(host='python-2pb1kf.chbk.run', port=80): Max retries exceeded with url: /vmess/sub (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fb4b8dd57b0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))"
http://fjcm.121628.xyz/sub/1116.txt,0,失败,请求超时
http://37.32.27.116:8080/ssr/sub,0,失败,请求超时
http://110.72.100.27:55/api/v1/client/subscribe?token=b5c6af703a58cf950498c03e7a42a0f2,0,失败,请求超时
http://113.31.116.212:13800/api/v1/client/subscribe?token=b5d84c66256755e551704d05600ada67,0,失败,请求超时
https://api.heima2u.com/api/v1/client/subscribe?token=54cadb31c561a28c8d1f4d16ceac5c50,0,失败,请求超时
https://api1.danidapigu.top/api/v1/client/subscribe?token=e1625b3640ff08f0dafb07e0360c6bf7,0,失败,请求超时
http://37.32.27.116:8080/clash/proxies,0,失败,请求超时
http://0dianyun3.xyz/link/HzWCyhjbs1QG1sip?clash=1,0,失败,请求超时
